const C3={
home:[
{t:'📈 趨勢',h:'環保可重複使用產品爆發，矽膠保鮮蓋登上全球銷量冠軍',p:'OXO 矽膠保鮮蓋以 42% 回購率登上 2026 全球銷量第一。消費者從一次性用品轉向可重複使用的環保替代品，矽膠廚具、蜂蠟保鮮布、可重複使用食物袋需求持續爆發。',src:'https://www.alibaba.com/product-insights/top-amazon-best-selling-products-2026-market-trends-regional-breakdown-and-strategic-insights.html',products:['OXO Good Grips Silicone Stretch Lids 12-Pack','Stasher Reusable Silicone Food Storage Bag','Bee\'s Wrap Reusable Beeswax Food Wraps']},
{t:'📈 趨勢',h:'天然材質與大地色系居家風格取代冷調極簡',p:'消費者從冷調極簡風轉向溫暖大地色系與天然材質（木質、藤編、亞麻）。收納用品、香氛蠟燭、極簡裝飾品持續熱銷。模組化收納系統搜尋量年增 35%+。',src:'https://www.accio.com/business/latest-best-seller-home-and-kitchen',products:['Mkono Macrame Wall Hanging Shelf','Yankee Candle Signature Collection','mDesign Stackable Closet Organizer Bins']},
{t:'📈 趨勢',h:'智慧香氛擴散器與情境照明成為居家氛圍新標配',p:'WiFi 控制的精油擴散器與可調色溫 LED 燈條搜尋量年增 28%。消費者追求「居家 spa 體驗」，薰衣草、尤加利精油組合包銷量穩定。智慧插座搭配定時功能讓情境照明自動化。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['ASAKUKI 500ml Essential Oil Diffuser','Govee RGBIC LED Strip Lights 65.6ft','Lagunamoon Essential Oils Gift Set 6-Pack']},
{t:'📈 趨勢',h:'TikTok #CleanTok 持續帶動清潔神器銷量，Scrub Daddy 穩居熱銷',p:'#CleanTok 標籤累計超過 800 億次觀看，持續為清潔用品帶來流量。Scrub Daddy、The Pink Stuff、電動清潔刷等「網紅清潔神器」在 Amazon 上長期佔據 Best Seller。消費者偏好視覺效果強的清潔產品。',src:'https://whop.com/blog/amazon-trends/',products:['Scrub Daddy Original Sponge 8-Pack','The Pink Stuff Miracle Cleaning Paste','Lefree Electric Spin Scrubber']},
{t:'📈 趨勢',h:'Subscribe & Save 推動居家消耗品訂閱制，垃圾袋與洗衣球回購率最高',p:'Amazon Subscribe & Save 在 Home 品類滲透率持續提升。垃圾袋、洗碗精、洗衣球等消耗品訂閱回購率超過 60%。品牌透過訂閱折扣鎖定長期客戶，降低獲客成本。',src:'https://supplykick.com/blog/amazon-subscribe-and-save',products:['Glad ForceFlex Tall Kitchen Trash Bags','Tide PODS Laundry Detergent Pacs','Finish Quantum Dishwasher Detergent']},
{t:'📈 趨勢',h:'Gen Z 租屋族推動「可拆卸」居家裝飾需求，壁貼與無痕掛鉤爆發',p:'Gen Z 租屋族無法釘牆，推動可拆卸壁貼、無痕掛鉤、磁吸式收納架需求。Peel-and-stick 壁紙搜尋量年增 45%。臨時性裝飾品（節日主題、季節更換）也受歡迎。',src:'https://explodingtopics.com/blog/trending-products',products:['Command Picture Hanging Strips Variety Pack','RoomMates Peel and Stick Wallpaper','FECA Suction Cup Hooks Heavy Duty']},
{t:'📈 趨勢',h:'寵物友善居家用品成為新興子品類，防抓沙發套與寵物階梯熱銷',p:'94M 美國家庭養寵物，推動「寵物友善」居家用品需求。防抓沙發套、寵物專用毯、寵物階梯（幫助老犬上床）銷量穩定成長。消費者願意為寵物友善設計支付溢價。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Easy-Going Stretch Sofa Slipcover','PetSafe CozyUp Folding Pet Steps','Bedsure Waterproof Dog Blanket']},
{t:'📈 趨勢',h:'$15-25 價位帶居家小物最容易衝動購買，禮品場景推動銷量',p:'數據顯示 $15-25 是 Home 品類衝動購買甜蜜點。香氛蠟燭、裝飾托盤、相框組合等「輕奢小物」在母親節、聖誕節等禮品季銷量翻倍。禮盒包裝版本轉換率比普通版高 30%。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Chesapeake Bay Candle Scented Candle','Umbra Prisma Photo Frame Set','Kate Aspen Gold Geometric Tray']},
{t:'📈 趨勢',h:'Climate Pledge Friendly 標章產品曝光率提升，環保認證成為競爭優勢',p:'Amazon Climate Pledge Friendly 標章產品在搜尋結果中獲得額外曝光。通過 EPEAT、FSC、OEKO-TEX 等認證的居家用品點擊率高出 15%。消費者願意為環保認證產品多付 10-15%。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Seventh Generation Dish Soap','If You Care Parchment Baking Paper','Full Circle Recycled Cleaning Cloths']}
],
home_improvement:[
{t:'📈 趨勢',h:'91% 美國屋主計畫裝修，智慧家居配件走向平價必備',p:'根據 Houzz 報告，91% 屋主計畫 2026 年裝修。智慧燈泡、智慧插座、動態感應器價格持續下降，$15-30 價位帶成長最快。DIY 工具組透過 TikTok 爆紅帶動 Amazon 銷量。',src:'https://www.accio.com/business/amazon-best-selling-home-improvement',products:['Philips Hue White & Color Ambiance Starter Kit','TP-Link Kasa Smart Plug Mini (4-Pack)','DEWALT 20V MAX Cordless Drill Combo Kit']},
{t:'📈 趨勢',h:'無線電動工具持續取代有線款，女性/公寓住戶工具組崛起',p:'鋰電池技術進步推動無線電鑽、電動螺絲起子成長。針對女性/公寓住戶的輕量化、設計感工具組在社群上傳播力強，粉色工具組成為爆品。',src:'https://accio.com/business/amazon-best-seller-tool-kit',products:['WORKPRO Pink Tool Kit 237-Piece','BLACK+DECKER 20V MAX Drill/Driver','Bosch 25-Piece Screwdriver Bit Set']},
{t:'📈 趨勢',h:'節能改造需求上升，LED 燈具與智慧溫控器成為裝修首選',p:'美國能源成本上升推動節能改造需求。LED 吸頂燈、智慧溫控器、窗戶隔熱膜搜尋量年增 22%。Energy Star 認證產品在 Amazon 上獲得更高轉換率。政府節能補貼也推動消費者升級。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Google Nest Learning Thermostat','Hykolity 13 inch LED Flush Mount Ceiling Light','Gila Heat Control Window Film']},
{t:'📈 趨勢',h:'水質過濾與淨水設備需求穩定成長，DIY 安裝款最受歡迎',p:'消費者對自來水品質關注度提升，推動水龍頭濾水器、全屋淨水系統、冰箱濾芯需求。DIY 免工具安裝款銷量最高。Subscribe & Save 濾芯替換服務回購率超過 70%。',src:'https://supplykick.com/blog/amazon-home-improvement-trends',products:['Brita Faucet Water Filter System','APEC Water Systems 5-Stage Reverse Osmosis','Waterdrop Refrigerator Water Filter']},
{t:'📈 趨勢',h:'居家安全設備平價化，影像門鈴與感應燈年銷量破紀錄',p:'Ring Video Doorbell 與 Blink 攝影機持續主導居家安全品類。太陽能感應燈、窗戶警報器等低價安全設備銷量年增 30%。$20-50 價位帶入門安全設備成長最快。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Ring Video Doorbell 4','Blink Outdoor 4 Security Camera','LITOM Solar Lights Outdoor 4-Pack']},
{t:'📈 趨勢',h:'浴室翻新成為最熱門 DIY 項目，花灑頭與浴室收納架熱銷',p:'浴室翻新是美國屋主最常進行的 DIY 項目。高壓花灑頭、浴室角落收納架、LED 浴室鏡搜尋量持續上升。$30-80 價位帶的「輕裝修」產品最受歡迎，無需請水電工即可安裝。',src:'https://www.accio.com/business/amazon-best-selling-home-improvement',products:['SparkPod High Pressure Rain Shower Head','KINCMAX Shower Caddy Basket Shelf','Keonjinn LED Bathroom Mirror 36x28']},
{t:'📈 趨勢',h:'車庫與儲藏空間整理成為新趨勢，壁掛式收納系統銷量翻倍',p:'遠端工作讓車庫變成多功能空間，推動車庫收納系統需求。壁掛式工具架、天花板儲物架、標籤機搜尋量年增 40%。「車庫改造」在 YouTube 上是熱門內容主題。',src:'https://whop.com/blog/amazon-trends/',products:['Rubbermaid FastTrack Garage Storage System','FLEXIMOUNTS Overhead Garage Storage Rack','DYMO LetraTag Label Maker']},
{t:'📈 趨勢',h:'油漆與牆面處理 DIY 工具組熱銷，消費者偏好一站式套組',p:'DIY 油漆工具組（滾筒+刷子+遮蔽膠帶+防護布）銷量穩定。消費者偏好「一站式」套組而非單品購買。可水洗矽膠油漆盤、無滴漏滾筒等創新產品獲得高評價。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Wagner Spraytech Control Spray Max','FrogTape Multi-Surface Painting Tape','Purdy White Dove Paint Roller Cover']},
{t:'📈 趨勢',h:'Matter 智慧家居協議推動跨品牌相容，消費者更願意投資智慧家居',p:'Matter 協議讓不同品牌智慧家居設備互通，降低消費者選擇障礙。支援 Matter 的智慧燈泡、門鎖、感應器銷量成長快於非 Matter 產品。Apple Home、Google Home、Alexa 三大平台相容性成為賣點。',src:'https://helium10.com/blog/amazon-smart-home-trends',products:['Eve Motion Sensor (Matter)','Nanoleaf Essentials Smart Bulb (Matter)','Yale Assure Lock 2 (Matter)']}
],

kitchen:[
{t:'📈 趨勢',h:'保溫杯熱潮持續，Owala FreeSip 登上 Kitchen #1 Best Seller',p:'Lifestyle Hydration 主導 Kitchen 品類。Owala FreeSip 以 111,350+ 評論登上 #1。Stanley Quencher 穩居 Top 5。數位廚房工具（精準溫度計、數位秤）是第二大主題。',src:'https://www.accio.com/business/top-selling-kitchen-items-on-amazon',products:['Owala FreeSip Insulated Water Bottle','Stanley Quencher H2.0 FlowState Tumbler 40oz','ThermoPro TP19H Digital Meat Thermometer']},
{t:'📈 趨勢',h:'PFAS 疑慮推動天然材質廚具取代不沾鍋',p:'消費者擔憂不沾塗層化學物質（PFAS），碳鋼鍋、鑄鐵鍋、木質砧板需求上升。Amazon Kitchen 預估 2028 年營收達 $1,500 億。竹製餐具與矽膠廚具也在成長。',src:'https://www.accio.com/business/amazon-best-selling-kitchen',products:['Lodge Pre-Seasoned Cast Iron Skillet','Totally Bamboo Original Cutting Board','OXO Good Grips Silicone Spatula Set']},
{t:'📈 趨勢',h:'氣炸鍋配件生態系持續擴張，矽膠內鍋墊與分隔盤成為爆品',p:'氣炸鍋滲透率已超過 60% 美國家庭，配件市場隨之爆發。矽膠內鍋墊、分隔烤盤、烘焙紙墊搜尋量年增 50%+。配件單價低（$8-15）但回購率高，適合新賣家切入。',src:'https://explodingtopics.com/blog/trending-products',products:['COSORI Air Fryer Silicone Liners 2-Pack','Air Fryer Divider Insert Silicone','Air Fryer Parchment Paper Liners 200-Pack']},
{t:'📈 趨勢',h:'冷萃咖啡與手沖咖啡器具需求上升，居家咖啡文化深化',p:'冷萃咖啡壺、手沖濾杯、電動磨豆機搜尋量持續成長。消費者從速溶咖啡升級到精品咖啡體驗。$30-60 價位帶的入門手沖套組最受歡迎。咖啡訂閱服務也帶動器具銷量。',src:'https://www.accio.com/business/top-selling-kitchen-items-on-amazon',products:['Hario V60 Drip Coffee Pour Over Set','Takeya Patented Cold Brew Coffee Maker','Baratza Encore ESP Coffee Grinder']},
{t:'📈 趨勢',h:'便當盒與食物準備容器受健身族群與上班族推動',p:'Meal Prep 文化推動玻璃保鮮盒、分格便當盒、沙拉罐需求。健身族群偏好可微波、可洗碗機的玻璃容器。Bento Box 風格便當盒在社群上傳播力強，帶動 Amazon 銷量。',src:'https://whop.com/blog/amazon-trends/',products:['Prep Naturals Glass Meal Prep Containers 5-Pack','Bentgo Modern Bento-Style Lunch Box','Rubbermaid Brilliance Food Storage Set']},
{t:'📈 趨勢',h:'廚房智慧小家電整合 App 控制，精準烹飪成為主流',p:'Sous Vide 循環加熱器、智慧烤箱、App 控制慢燉鍋等精準烹飪設備銷量穩定成長。消費者追求「餐廳級」料理體驗。WiFi 連接與食譜 App 整合成為產品差異化關鍵。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Anova Culinary Sous Vide Precision Cooker','Instant Pot Pro Plus WiFi Smart Pressure Cooker','MEATER Plus Wireless Meat Thermometer']},
{t:'📈 趨勢',h:'日式與韓式廚具在美國市場快速成長，文化輸出帶動需求',p:'韓劇與日本料理節目推動日韓廚具需求。日式刀具（三德刀、出刃刀）、韓式石鍋、日式鑄鐵茶壺搜尋量年增 35%。亞洲食材（味噌、韓式辣醬）在 Grocery 品類也同步成長。',src:'https://www.accio.com/business/amazon-best-selling-kitchen',products:['Tojiro DP Series Santoku Knife','KOREANJOY Premium Dolsot Stone Bowl','TOPTIER Japanese Cast Iron Teapot']},
{t:'📈 趨勢',h:'可堆疊收納與廚房空間最大化產品持續熱銷',p:'美國公寓面積縮小推動廚房收納需求。可堆疊調味罐架、磁吸式刀架、水槽上方瀝水架是熱門品項。「小廚房改造」在 Pinterest 上是熱門搜尋主題，帶動 Amazon 相關產品銷量。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['SpaceAid Pull Out Spice Rack Organizer','SimpleHouseware Over Sink Dish Drying Rack','Magnetic Knife Strip Holder 16 Inch']},
{t:'📈 趨勢',h:'兒童友善廚具與親子烘焙套組在假日季銷量翻倍',p:'家長尋找與孩子互動的活動，推動兒童安全刀具、迷你烘焙套組、造型模具需求。聖誕節與暑假是銷售高峰。兒童圍裙與廚師帽套組作為禮品銷量穩定。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Tovla Jr. Kids Kitchen Knife Set','Baketivity Kids Baking Kit','Curious Chef 11-Piece Kids Cookware Set']}
],
lawn_garden:[
{t:'📈 趨勢',h:'城市園藝（Urban Gardening）持續熱門，智慧灌溉與植物生長燈需求上升',p:'自動澆水器、植物生長燈、智慧土壤感測器搜尋量持續成長。有機肥料、可降解花盆等環保園藝產品成長快速。室內植物配件是全年穩定需求品類。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['VIVOSUN LED Grow Light','Blumat Classic Plant Watering Stakes','XLUX Soil Moisture Meter']},
{t:'📈 趨勢',h:'電動割草機與無線園藝工具取代燃油款，環保法規推動轉型',p:'加州等州禁止銷售新燃油園藝設備，推動電動割草機、無線修枝剪、電動吹葉機需求。40V/56V 電池平台成為主流。Greenworks 與 EGO 品牌在 Amazon 上銷量領先。',src:'https://www.accio.com/business/amazon-best-selling-lawn-garden',products:['EGO Power+ 56V Cordless Lawn Mower','Greenworks 40V Cordless String Trimmer','BLACK+DECKER 20V MAX Cordless Hedge Trimmer']},
{t:'📈 趨勢',h:'Raised Garden Bed 搜尋量年增 40%，居家種菜成為生活方式',p:'食品價格上漲與健康意識推動居家種菜需求。Raised Garden Bed（高架花圃）搜尋量年增 40%。搭配有機種子、堆肥箱、園藝手套的套組銷量最高。YouTube 園藝教學頻道帶動新手入門。',src:'https://explodingtopics.com/blog/trending-products',products:['Best Choice Products Raised Garden Bed 8x2ft','Miracle-Gro Raised Bed Soil','Sow Right Seeds Vegetable Garden Seed Collection']},
{t:'📈 趨勢',h:'戶外生活空間延伸，庭院燈串與戶外家具配件 Q2-Q3 季節性爆發',p:'美國消費者將庭院視為「戶外客廳」，推動庭院燈串、戶外地毯、遮陽傘需求。Q2-Q3 是銷售高峰，提前備貨至關重要。太陽能庭院燈是全年穩定銷售品項。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Brightown Outdoor String Lights 100ft','Reversible Mats Outdoor Patio Rug','Sunnyglade 9ft Patio Umbrella']},
{t:'📈 趨勢',h:'有機與天然除蟲產品需求上升，消費者避免化學農藥',p:'消費者對化學農藥的健康疑慮推動有機除蟲產品需求。矽藻土、印楝油、天然驅蟲噴霧搜尋量年增 25%。寵物安全與兒童安全是消費者選購的首要考量。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Neem Bliss Pure Neem Oil','Harris Diatomaceous Earth','Wondercide Natural Indoor Pest Control Spray']},
{t:'📈 趨勢',h:'智慧灑水系統與 WiFi 花園監控成為科技園藝新趨勢',p:'Rachio 與 Orbit B-hyve 等智慧灑水控制器銷量穩定成長。WiFi 土壤感測器、氣象站、花園攝影機讓園藝數據化。與 Alexa/Google Home 整合是重要賣點。',src:'https://helium10.com/blog/amazon-garden-trends',products:['Rachio 3 Smart Sprinkler Controller','Orbit B-hyve WiFi Sprinkler Timer','Ambient Weather WS-2902 WiFi Weather Station']},
{t:'📈 趨勢',h:'室內水耕系統（Hydroponics）從小眾走向主流，AeroGarden 穩居 #1',p:'室內水耕系統讓消費者全年種植香草與蔬菜。AeroGarden 系列穩居品類 #1。LED 生長燈技術進步降低成本。「Farm to Table」概念推動消費者嘗試居家種植。',src:'https://whop.com/blog/amazon-trends/',products:['AeroGarden Harvest Indoor Garden','iDOO Hydroponics Growing System 12 Pods','Click & Grow Smart Garden 9']},
{t:'📈 趨勢',h:'堆肥與廚餘處理設備需求上升，環保意識推動零廢棄生活',p:'廚餘堆肥桶、電動廚餘處理機、蚯蚓堆肥箱搜尋量年增 30%。Lomi 電動廚餘處理機在社群上獲得大量關注。零廢棄生活方式推動相關產品需求持續成長。',src:'https://explodingtopics.com/blog/trending-products',products:['Lomi Smart Waste Kitchen Composter','Epica Stainless Steel Compost Bin','FCMP Outdoor Tumbling Composter']},
{t:'📈 趨勢',h:'鳥類觀察與野生動物花園成為新興嗜好，餵鳥器銷量穩定',p:'COVID 後「後院觀鳥」成為美國熱門嗜好。智慧餵鳥器（附攝影機）、蜂鳥餵食器、鳥浴盆銷量穩定。Bird Buddy 智慧餵鳥器在 Kickstarter 爆紅後轉戰 Amazon。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Bird Buddy Smart Bird Feeder','Perky-Pet Hummingbird Feeder','VIVOHOME Polyresin Antique Bird Bath']}
],

appliances:[
{t:'📈 趨勢',h:'小型廚房家電持續熱銷，智慧連網功能成為新標準',p:'氣炸鍋、迷你果汁機、便攜式咖啡機穩居 Best Seller。Vitamix E310 是 2026 全球第四暢銷品。Energy Star 認證與 WiFi 控制功能成為消費者選購考量。製冰機意外成為爆品。',src:'https://www.alibaba.com/product-insights/top-amazon-best-selling-products-2026-market-trends-regional-breakdown-and-strategic-insights.html',products:['COSORI Air Fryer Pro LE 5-Qt','Vitamix E310 Explorian Blender','EUHOMY Countertop Ice Maker Machine']},
{t:'📈 趨勢',h:'個人化小家電崛起，迷你洗衣機與桌上型洗碗機受小家庭歡迎',p:'單身與小家庭推動迷你家電需求。桌上型洗碗機、迷你洗衣機、小型除濕機搜尋量年增 35%。$150-300 價位帶成長最快。公寓友善尺寸是關鍵賣點。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['COMFEE Countertop Dishwasher','COSTWAY Portable Washing Machine','hOmeLabs Small Space Dehumidifier']},
{t:'📈 趨勢',h:'空氣品質設備需求穩定成長，HEPA 空氣清淨機與加濕器是長青品',p:'野火煙霧、過敏季節推動空氣清淨機需求。HEPA 13 濾網成為基本要求。智慧空氣品質監測功能加分。加濕器在冬季銷量翻倍。濾網替換是高利潤回購品項。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Levoit Core 300S Smart Air Purifier','LEVOIT Classic 300S Smart Humidifier','Coway Airmega 400S Smart Air Purifier']},
{t:'📈 趨勢',h:'機器人吸塵器價格持續下降，$200 以下入門款銷量爆發',p:'機器人吸塵器從奢侈品變為必需品。$200 以下入門款銷量年增 45%。LiDAR 導航、自動集塵座、拖地功能下放到中價位。iRobot Roomba 與 roborock 主導市場。',src:'https://www.accio.com/business/amazon-best-selling-appliances',products:['roborock Q7 Max+ Robot Vacuum','iRobot Roomba j7+ Self-Emptying Robot Vacuum','Shark AI Ultra Robot Vacuum']},
{t:'📈 趨勢',h:'咖啡機市場兩極化：膠囊機便利 vs 義式半自動追求品質',p:'Nespresso 膠囊機穩居便利派首選。同時 Breville/De\'Longhi 義式半自動咖啡機銷量也在成長，反映消費者對咖啡品質的追求。$100-200 與 $400-600 兩個價位帶成長最快。',src:'https://www.accio.com/business/amazon-best-selling-appliances',products:['Nespresso Vertuo Next Coffee Machine','Breville Barista Express Espresso Machine','De\'Longhi Stilosa Manual Espresso Machine']},
{t:'📈 趨勢',h:'食物保存設備需求上升，真空封口機與冷凍乾燥機受 Prepper 族群推動',p:'食品價格上漲與「預備者」（Prepper）文化推動食物保存設備需求。真空封口機銷量穩定。家用冷凍乾燥機雖然高單價（$2,000+）但搜尋量年增 60%。批量購買與食物保存成為趨勢。',src:'https://explodingtopics.com/blog/trending-products',products:['FoodSaver V4400 Vacuum Sealer Machine','Harvest Right Home Freeze Dryer','NutriChef Vacuum Sealer Bags 100-Pack']},
{t:'📈 趨勢',h:'靜音設計成為家電新賣點，消費者願意為低噪音支付溢價',p:'遠端工作讓消費者對家電噪音更敏感。標榜「超靜音」的洗碗機、冰箱、空氣清淨機獲得更高評價。噪音分貝數成為產品比較的重要指標。靜音風扇在夏季銷量翻倍。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Dreo Tower Fan 42 inch Quiet','Bosch 300 Series Dishwasher','Honeywell QuietSet Tower Fan']},
{t:'📈 趨勢',h:'復古風格小家電成為廚房裝飾品，Smeg 風格平價替代品熱銷',p:'復古風格（Retro）烤麵包機、電熱水壺、攪拌機在社群上傳播力強。Smeg 風格但價格僅 1/3 的平價替代品在 Amazon 上銷量驚人。粉色、薄荷綠、奶油白是最受歡迎色系。',src:'https://whop.com/blog/amazon-trends/',products:['Galanz Retro Electric Toaster','Paris Rhône Retro Electric Kettle','Nostalgia Retro Stand Mixer']},
{t:'📈 趨勢',h:'Prime Day 與 Black Friday 是家電品類最大折扣季，提前備貨至關重要',p:'家電品類在 Prime Day 與 Black Friday 銷量可達平日 5-8 倍。消費者會等待折扣季購買高單價家電。提前 2-3 個月備貨、設定 Coupon 與 Lightning Deal 是關鍵策略。',src:'https://junglescout.com/blog/amazon-prime-day-trends/',products:['Instant Pot Duo 7-in-1 Electric Pressure Cooker','Ninja Foodi 6-in-1 Indoor Grill','KitchenAid Artisan Series Stand Mixer']}
],
tools:[
{t:'📈 趨勢',h:'入門級工具組透過 TikTok 爆紅，$20-30 與 $80-120 兩極化發展',p:'社群媒體帶動「essentials」工具組銷量。同時「入門專業級」工具組回購率高。無線電動工具持續取代有線款，20V 平台相容性成為賣點。',src:'https://accio.com/business/amazon-best-seller-tool-kit',products:['DEKOPRO 168-Piece Tool Kit','Milwaukee M18 Cordless Drill Kit','Bosch PS31-2A 12V Drill/Driver Kit']},
{t:'📈 趨勢',h:'精密量測工具需求上升，雷射水平儀與數位捲尺成為 DIY 必備',p:'DIY 裝修熱潮推動精密量測工具需求。雷射水平儀從專業工具變為家用必備。數位捲尺、角度測量器、管道探測器搜尋量年增 20%。$20-50 價位帶最受歡迎。',src:'https://www.accio.com/business/amazon-best-selling-tools',products:['HUEPAR Self-Leveling Laser Level','DITRON Digital Tape Measure','Klein Tools Non-Contact Voltage Tester']},
{t:'📈 趨勢',h:'電動螺絲起子成為家庭必備，輕量化設計吸引非專業用戶',p:'電動螺絲起子從專業工具轉型為家庭必備品。重量低於 1 磅、USB-C 充電、附帶多種批頭的款式最受歡迎。女性消費者佔購買比例 40%+。開箱組裝家具是最常見使用場景。',src:'https://whop.com/blog/amazon-trends/',products:['HOTO Electric Screwdriver','Xiaomi Mi Cordless Screwdriver','WORX WX240L 4V Cordless Screwdriver']},
{t:'📈 趨勢',h:'焊接與金工 DIY 從小眾走向主流，YouTube 教學帶動入門設備銷量',p:'YouTube 與 TikTok 上的金工 DIY 內容帶動焊接機、研磨機、金屬切割工具需求。入門級 MIG 焊接機（$150-300）銷量年增 30%。安全裝備（焊接面罩、手套）同步成長。',src:'https://explodingtopics.com/blog/trending-products',products:['YESWELDER MIG-205DS Welding Machine','DEWALT Angle Grinder 4-1/2 inch','Lincoln Electric Auto-Darkening Welding Helmet']},
{t:'📈 趨勢',h:'工具收納與整理系統需求穩定，模組化工具箱成為賣點',p:'消費者購買工具後需要收納解決方案。模組化工具箱（可堆疊、可連接）銷量穩定。Milwaukee PACKOUT 與 DeWalt TOUGHSYSTEM 系統帶動品類成長。壁掛式工具板也受歡迎。',src:'https://supplykick.com/blog/amazon-tools-trends',products:['Milwaukee PACKOUT Modular Tool Box','DeWalt TOUGHSYSTEM 2.0 Tool Box','Pegboard Wall Organizer Kit']},
{t:'📈 趨勢',h:'3D 列印工具與配件在 Amazon 上快速成長，Maker 文化推動需求',p:'入門級 3D 列印機價格降至 $200 以下，推動 Maker 文化普及。3D 列印耗材（PLA/PETG）、噴嘴、建構板等配件銷量年增 40%。Creality 與 Bambu Lab 品牌在 Amazon 上領先。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Creality Ender-3 V3 SE 3D Printer','Bambu Lab A1 Mini 3D Printer','SUNLU PLA 3D Printer Filament 1kg']},
{t:'📈 趨勢',h:'安全裝備銷量與工具銷量正相關，護目鏡與工作手套是必搭配件',p:'Amazon 演算法推薦「經常一起購買」帶動安全裝備銷量。護目鏡、工作手套、耳塞是最常見搭配品項。OSHA 安全標準認證成為賣點。Bundle 組合銷售轉換率高於單品。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['3M Safety Glasses Anti-Fog','Mechanix Wear Original Work Gloves','3M WorkTunes Hearing Protector with Bluetooth']},
{t:'📈 趨勢',h:'季節性工具需求明顯：Q1 稅務退款帶動大型工具購買',p:'美國消費者在 Q1 收到稅務退款後傾向購買大型工具。電動工具組合套裝在 2-4 月銷量最高。Q2-Q3 戶外工具（鏈鋸、修枝剪）需求上升。Q4 工具禮盒組銷量爆發。',src:'https://junglescout.com/blog/amazon-seasonal-trends/',products:['DEWALT 20V MAX Combo Kit 10-Tool','Husqvarna 120 Mark II Chainsaw','Craftsman Mechanics Tool Set 230-Piece']}
],

automotive:[
{t:'📈 趨勢',h:'MagSafe 車用支架與 EV 配件需求雙引擎成長',p:'MagSafe 車用支架、後座收納袋、車用吸塵器是長青熱銷品。EV 充電線收納、車用行動電源、電動車專用腳踏墊等新品類正在形成，競爭尚未白熱化。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['iOttie Easy One Touch 5 Car Mount','Lusso Gear Car Seat Organizer','ThisWorx Car Vacuum Cleaner']},
{t:'📈 趨勢',h:'車內空氣品質與香氛產品需求上升，消費者追求駕駛體驗升級',p:'車用空氣清淨機、香氛擴散器、活性碳除臭包搜尋量年增 25%。消費者從傳統樹形芳香劑升級到精油擴散器。高質感車用香氛成為社群熱門分享內容。',src:'https://whop.com/blog/amazon-trends/',products:['PURGGO Car Air Freshener Bamboo Charcoal','Yankee Candle Car Jar Ultimate','Diptyque Car Diffuser with Baies Insert']},
{t:'📈 趨勢',h:'行車記錄器需求穩定，4K 解析度與前後雙鏡頭成為標配',p:'保險理賠需求與安全意識推動行車記錄器銷量。4K 解析度、前後雙鏡頭、夜視功能成為消費者基本要求。$50-120 價位帶成長最快。Viofo 與 Rexing 品牌在 Amazon 上領先。',src:'https://www.accio.com/business/amazon-best-selling-automotive',products:['Viofo A129 Pro Duo 4K Dash Cam','Rexing V1 4K Ultra HD Dash Cam','Garmin Dash Cam Mini 2']},
{t:'📈 趨勢',h:'Tesla 與 EV 專用配件市場快速成長，競爭者仍少',p:'Tesla Model 3/Y 車主數量持續增加，推動專用配件需求。中控台收納盒、螢幕保護貼、後備箱收納墊是熱銷品。EV 充電轉接頭、便攜式充電器也在成長。市場仍處於早期階段。',src:'https://explodingtopics.com/blog/trending-products',products:['BASENOR Tesla Model 3/Y Center Console Organizer','Spigen Tesla Model 3/Y Screen Protector','Lectron Tesla to J1772 Charging Adapter']},
{t:'📈 趨勢',h:'車用手機配件生態系持續擴張，無線充電支架成為標配',p:'Qi2/MagSafe 無線充電車用支架取代傳統夾式支架。通風口式、吸盤式、儀表板式三種安裝方式各有市場。$20-40 價位帶銷量最高。Apple CarPlay/Android Auto 相容性是加分項。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['ESR HaloLock MagSafe Car Charger Mount','Anker 613 Magnetic Wireless Car Charger','LISEN MagSafe Car Mount for iPhone']},
{t:'📈 趨勢',h:'汽車清潔與美容（Detailing）產品受 YouTube 社群推動',p:'汽車美容 YouTube 頻道（如 ChrisFix）帶動 DIY 洗車與美容產品需求。陶瓷鍍膜噴霧、超細纖維布、泡沫噴槍搜尋量年增 30%。消費者從洗車場轉向 DIY 美容。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Adam\'s Polishes Ceramic Spray Coating','Chemical Guys Microfiber Towels 12-Pack','MATCC Foam Cannon for Pressure Washer']},
{t:'📈 趨勢',h:'車用緊急工具包與安全裝備是全年穩定銷售品項',p:'車用緊急工具包（跳電線、拖車繩、急救包）是全年穩定需求品項。冬季暴風雪與夏季高溫季節銷量上升。父親節是重要禮品銷售時機。Bundle 組合銷售轉換率高。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['HAIPHAIK Emergency Roadside Kit','NOCO Boost Plus GB40 Jump Starter','First Aid Only 299-Piece Emergency Kit']},
{t:'📈 趨勢',h:'寵物車用配件需求上升，後座保護墊與寵物安全帶熱銷',p:'94M 美國家庭養寵物，帶寵物出行推動車用寵物配件需求。後座防護墊、寵物安全帶、車窗遮陽簾搜尋量年增 20%。寵物旅行水碗與便攜式食物容器也在成長。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Active Pets Dog Back Seat Cover Protector','SlowTon Dog Car Harness Seatbelt','Pecute Dog Car Window Shade 2-Pack']},
{t:'📈 趨勢',h:'LED 車燈升級套件銷量穩定，消費者追求更亮更安全的照明',p:'LED 頭燈升級套件、LED 霧燈、車內氛圍燈條搜尋量穩定。消費者從鹵素燈升級到 LED 追求更好的夜間能見度。$20-50 價位帶的即插即用款式最受歡迎。',src:'https://helium10.com/blog/amazon-automotive-trends',products:['SEALIGHT LED Headlight Bulbs H11','Govee Interior Car LED Strip Lights','Auxbeam LED Fog Light Bulbs']}
],
furniture:[
{t:'📈 趨勢',h:'模組化小空間家具與 Japandi 風格持續主導線上家具銷售',p:'易組裝、模組化、適合小空間的家具銷量持續成長。Japandi 風格（日式+北歐）——簡約線條、天然木質、中性色調在美國市場持續受歡迎。書架、電腦桌、收納櫃是熱門品項。',src:'https://www.clickpost.ai/blog/online-shopping-categories',products:['VASAGLE Industrial Bookshelf','CubiCubi Computer Desk 47 inch','SONGMICS Cube Storage Organizer']},
{t:'📈 趨勢',h:'Home Office 家具需求常態化，升降桌銷量年增 25%',p:'遠端工作常態化推動 Home Office 家具持續成長。電動升降桌從奢侈品變為標配。$200-400 價位帶成長最快。人體工學椅、螢幕支架、桌下收納架是常見搭配購買品項。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['FEZIBO Electric Standing Desk 48x24','Hbada Ergonomic Office Chair','VIVO Dual Monitor Desk Mount']},
{t:'📈 趨勢',h:'戶外家具在 Q2-Q3 季節性爆發，Adirondack 椅與吊床是熱門品項',p:'戶外家具在春夏季銷量可達冬季 4-5 倍。Adirondack 椅、戶外吊床、摺疊露營椅是熱門品項。HDPE 材質（耐候、免維護）取代傳統木質。提前至 Q1 備貨是關鍵。',src:'https://www.accio.com/business/amazon-best-selling-furniture',products:['SERWALL HDPE Adirondack Chair','Vivere Double Cotton Hammock with Stand','Coleman Portable Camping Quad Chair']},
{t:'📈 趨勢',h:'床墊與寢具線上銷售持續成長，Bed-in-a-Box 模式主導市場',p:'Bed-in-a-Box 壓縮床墊讓線上購買床墊成為主流。記憶棉床墊、冷凝膠枕頭、竹纖維床單是熱銷品。$300-600 價位帶的中價位床墊成長最快。100 天試睡保證成為標配。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Zinus Green Tea Memory Foam Mattress','Beckham Hotel Collection Gel Pillows 2-Pack','Bedsure Cooling Bamboo Sheets Set']},
{t:'📈 趨勢',h:'兒童家具與學習空間設計需求上升，可調節書桌椅組合熱銷',p:'家長重視兒童學習環境，推動可調節高度書桌椅、書架、收納櫃需求。Montessori 風格低矮書架與玩具收納架在社群上受歡迎。安全圓角設計是消費者首要考量。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['VIVO Kids Height Adjustable Desk','ECR4Kids Birch Montessori Bookshelf','Delta Children MySize Bookshelf']},
{t:'📈 趨勢',h:'多功能沙發床與儲物家具受小空間住戶歡迎',p:'美國公寓面積縮小推動多功能家具需求。沙發床、儲物腳凳、摺疊餐桌搜尋量年增 30%。「一物多用」是消費者選購關鍵。$200-500 價位帶的中價位多功能家具成長最快。',src:'https://whop.com/blog/amazon-trends/',products:['Linenspa Memory Foam Futon Sofa Bed','SONGMICS Storage Ottoman Bench','Drop Leaf Folding Dining Table']},
{t:'📈 趨勢',h:'寵物家具成為新興子品類，貓跳台與狗窩設計感提升',p:'寵物主人希望寵物家具融入居家裝飾。設計感貓跳台、現代風格狗窩、窗台貓床搜尋量年增 35%。中性色調、天然材質的寵物家具獲得更高評價。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['FEANDREA Cat Tree Modern','Casper Dog Bed','MEWOOFUN Window Cat Perch']},
{t:'📈 趨勢',h:'組裝簡易度成為線上家具最重要評價指標',p:'Amazon 家具負評中「組裝困難」佔比最高。提供清晰說明書、預鑽孔、工具附帶的產品獲得更高評價。「15 分鐘組裝」成為有效行銷訴求。部分品牌開始提供免組裝（已組裝出貨）選項。',src:'https://supplykick.com/blog/amazon-furniture-trends',products:['Zinus SmartBase Bed Frame (No Tools Needed)','Walker Edison Modern Farmhouse TV Stand','Nathan James Theo 5-Shelf Bookcase']},
{t:'📈 趨勢',h:'復古工業風（Industrial Style）家具在美國市場持續受歡迎',p:'金屬框架搭配木質桌面的工業風家具在 Amazon 上銷量穩定。VASAGLE 品牌以工業風設計在 Amazon 上建立強勢地位。書架、電視櫃、玄關桌是最受歡迎品項。',src:'https://backlinko.com/ecommerce-stats',products:['VASAGLE Industrial Console Table','IRONCK Bookshelf Industrial','Walker Edison Rustic TV Stand 58 inch']}
],
baby:[
{t:'📈 趨勢',h:'有機棉與無毒材質成為基本門檻，智慧嬰兒監控器年增 25%+',p:'GOTS 認證有機棉、BPA-free 材質是消費者最低要求。智慧嬰兒監控器（WiFi 攝影機+呼吸偵測）銷量年增 25%+。Subscribe & Save 在 Baby 品類滲透率高，尿布與濕紙巾訂閱制成長快速。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Pampers Swaddlers Diapers (Subscribe & Save)','Nanit Pro Smart Baby Monitor','Burt\'s Bees Baby Organic Coveralls']},
{t:'📈 趨勢',h:'嬰兒副食品製作工具需求上升，家長偏好自製勝過市售',p:'家長對市售嬰兒食品添加物的疑慮推動自製副食品工具需求。嬰兒食物調理機、矽膠冷凍分裝盒、餵食湯匙組搜尋量年增 20%。「Baby Led Weaning」（BLW）餵食法在社群上流行。',src:'https://whop.com/blog/amazon-trends/',products:['BEABA Babycook Solo Baby Food Maker','WeeSprout Silicone Baby Food Freezer Tray','NumNum Pre-Spoon GOOtensils Baby Spoons']},
{t:'📈 趨勢',h:'嬰兒推車輕量化趨勢明顯，旅行系統與登機推車需求上升',p:'旅遊復甦推動輕量化登機推車需求。15 磅以下、單手收折、可放入飛機行李艙的推車搜尋量年增 30%。Travel System（推車+汽座組合）仍是新手父母首選。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Babyzen YOYO2 Stroller','Chicco Bravo 3-in-1 Travel System','Summer Infant 3Dlite Convenience Stroller']},
{t:'📈 趨勢',h:'Montessori 教育理念推動開放式玩具與學習環境產品需求',p:'Montessori 教育理念在美國家長中越來越受歡迎。木質開放式玩具、低矮書架、學習塔（Learning Tower）搜尋量年增 40%。天然材質、中性色調的嬰幼兒用品獲得更高評價。',src:'https://explodingtopics.com/blog/trending-products',products:['Lovevery The Play Kits','SDADI Kids Kitchen Step Stool Learning Tower','Melissa & Doug Wooden Building Blocks Set']},
{t:'📈 趨勢',h:'嬰兒睡眠安全產品需求穩定，透氣床墊與穿戴式毯子是熱銷品',p:'AAP 安全睡眠指南推動透氣嬰兒床墊、穿戴式睡袋（取代傳統毯子）需求。Newton Baby 透氣床墊與 Kyte Baby 竹纖維睡袋穩居 Best Seller。安全認證是消費者首要考量。',src:'https://www.accio.com/business/amazon-best-selling-baby',products:['Newton Baby Crib Mattress','Kyte Baby Sleep Bag','Halo SleepSack Wearable Blanket']},
{t:'📈 趨勢',h:'嬰兒護膚品天然成分趨勢，敏感肌專用產品成長快速',p:'家長對嬰兒護膚品成分越來越謹慎。無香料、無防腐劑、植物基成分的嬰兒乳液、屁屁膏、洗髮沐浴露需求上升。Tubby Todd、Pipette 等 Clean Baby 品牌在 Amazon 上快速成長。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Tubby Todd All Over Ointment','Pipette Baby Lotion','Mustela Stelatopia Emollient Cream']},
{t:'📈 趨勢',h:'二寶家庭推動雙人推車與兄弟姊妹共用產品需求',p:'美國二寶家庭比例穩定，推動雙人推車、推車踏板（讓大寶站立）、共用浴盆需求。Tandem（前後式）雙人推車比 Side-by-side（並排式）更受歡迎，因為更容易通過門框。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['UPPAbaby VISTA V2 Convertible Stroller','Lascal BuggyBoard Maxi Stroller Board','Skip Hop Moby Smart Sling 3-Stage Tub']},
{t:'📈 趨勢',h:'嬰兒用品禮盒組在 Baby Shower 季節銷量翻倍',p:'Baby Shower 文化推動嬰兒禮盒組需求。新生兒禮盒（包巾+帽子+手套+襪子）、尿布蛋糕、里程碑卡片組是熱門禮品。Q2-Q3 是 Baby Shower 高峰季。精美包裝提升轉換率。',src:'https://helium10.com/blog/amazon-baby-trends',products:['aden + anais Swaddle Blanket Gift Set','Honest Company Diaper Cake','Milestone Baby Cards Photo Cards Set']}
],

beauty:[
{t:'📈 趨勢',h:'K-beauty 與 Clean Beauty 主導，Mighty Patch 穩居 Amazon Beauty #1',p:'Beauty & Personal Care 是 Amazon 利潤最高品類（30%+ 賣家淨利超 21%）。K-beauty、Clean Beauty、抗老保養是三大方向。Mighty Patch 痘痘貼穩居 #1。Remineralizing Gum 搜尋量暴增 5100%，口腔保健跨界美容成為新趨勢。',src:'https://www.accio.com/business/beauty-bestseller',products:['Mighty Patch Original Pimple Patches','COSRX Snail Mucin 96% Power Essence','CeraVe Moisturizing Cream']},
{t:'📈 趨勢',h:'TikTok 驅動「病毒式」美妝產品，多功能一瓶多用需求上升',p:'社群媒體驅動的美妝產品週期越來越短但爆發力驚人。消費者偏好多功能產品（一瓶多用）。玻尿酸、菸鹼醯胺、維他命 C 是 Best Seller 中最常見的成分。全球美妝市場 2026 年預估成長 10%。',src:'https://www.accio.com/business/hot-selling-beauty-product',products:['The Ordinary Niacinamide 10% + Zinc 1%','TruSkin Vitamin C Serum','e.l.f. Halo Glow Liquid Filter']},
{t:'📈 趨勢',h:'男性美容保養市場快速成長，鬍鬚護理與男士護膚品需求上升',p:'男性美容保養市場年增 15%+。鬍鬚油、男士洗面乳、男士防曬乳搜尋量持續成長。社群媒體上「男士護膚 routine」內容帶動需求。$10-25 價位帶入門產品最受歡迎。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Honest Amish Beard Balm','Bulldog Original Face Wash','Every Man Jack SPF 50 Face Lotion']},
{t:'📈 趨勢',h:'防曬產品全年需求化，消費者從夏季限定轉向日常必備',p:'皮膚科醫師在社群上推廣「每日防曬」觀念，推動防曬產品從季節性轉為全年需求。SPF 50+ 輕透質地防曬乳最受歡迎。韓系防曬（如 Beauty of Joseon）在美國市場快速成長。',src:'https://explodingtopics.com/blog/trending-products',products:['Beauty of Joseon Relief Sun SPF50+','Supergoop! Unseen Sunscreen SPF 40','La Roche-Posay Anthelios Melt-In Sunscreen']},
{t:'📈 趨勢',h:'美容儀器從美容院走入家庭，LED 面膜與微電流設備熱銷',p:'家用美容儀器市場年增 20%+。LED 光療面膜、微電流提拉儀、射頻美容儀搜尋量持續上升。$50-150 價位帶入門款銷量最高。TikTok 上的「before/after」內容帶動購買。',src:'https://whop.com/blog/amazon-trends/',products:['CurrentBody Skin LED Light Therapy Mask','NuFACE Mini+ Microcurrent Facial Toning Device','FOREO BEAR Mini Microcurrent Facial Device']},
{t:'📈 趨勢',h:'頭皮護理成為新興美容子品類，頭皮精華液與去角質產品崛起',p:'消費者從「護髮」延伸到「護頭皮」。頭皮精華液、頭皮去角質磨砂膏、頭皮按摩梳搜尋量年增 45%。Briogeo 與 Olaplex 等品牌推出頭皮護理產品線。掉髮預防是主要消費動機。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Briogeo Scalp Revival Scrub Shampoo','The Ordinary Multi-Peptide Serum for Hair','HEETA Scalp Massager Shampoo Brush']},
{t:'📈 趨勢',h:'指甲彩繪 DIY 套組熱銷，凝膠指甲燈與貼片式美甲受歡迎',p:'美甲沙龍費用上漲推動 DIY 美甲需求。UV/LED 凝膠指甲燈、半固化凝膠貼片、美甲工具組搜尋量年增 35%。ohora 與 Beetles 品牌在 Amazon 上銷量領先。$15-30 入門套組最受歡迎。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Beetles Gel Nail Polish Kit with UV Light','ohora Semi Cured Gel Nail Strips','Modelones Gel Nail Polish Starter Kit']},
{t:'📈 趨勢',h:'Clean Beauty 認證成為購買決策關鍵，EWG 評分影響轉換率',p:'消費者越來越重視成分安全。EWG Verified、Leaping Bunny（無動物實驗）、Vegan 認證產品在 Amazon 上獲得更高轉換率。「成分透明」成為品牌差異化關鍵。Paraben-free、Sulfate-free 是基本要求。',src:'https://supplykick.com/blog/amazon-beauty-trends',products:['Drunk Elephant Protini Polypeptide Cream','Herbivore Botanicals Blue Tansy Mask','Pacifica Beauty Vegan Collagen Serum']},
{t:'📈 趨勢',h:'美容工具與配件利潤率高，冰球滾輪與 Gua Sha 持續熱銷',p:'美容工具利潤率通常高於護膚品。玉石 Gua Sha、冰球滾輪、矽膠洗臉刷是長青熱銷品。$8-20 價位帶衝動購買率高。禮盒包裝版本在節日季銷量翻倍。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['BAIMEI Jade Roller & Gua Sha Set','Ice Roller for Face & Eye Puffiness','FOREO LUNA 4 Mini Facial Cleansing Brush']}
],
grocery:[
{t:'📈 趨勢',h:'訂閱制推動回購，咖啡膠囊穩居 #1，異國風味與高蛋白食品崛起',p:'Nespresso 咖啡膠囊長期佔據 Grocery #1。Subscribe & Save 推動食品訂閱制爆發。消費者追求異國風味（韓式、日式、東南亞）、高蛋白、植物基食品。辣醬禮盒組銷量年增 40%+。',src:'https://www.accio.com/business/grocery-items-food-best-sellers',products:['Nespresso Capsules VertuoLine Variety Pack','Thoughtfully Gourmet Hot Sauce Gift Set 30-Pack','RXBAR Protein Bars Variety Pack']},
{t:'📈 趨勢',h:'韓式零食與日式糖果在美國市場爆發，文化輸出帶動食品銷量',p:'K-drama 與日本動漫推動韓式零食（辣炒年糕、海苔）與日式糖果（Hi-Chew、Pocky）在 Amazon 上銷量翻倍。「Asian Snack Box」綜合零食箱是熱門禮品。TikTok 試吃影片帶動流量。',src:'https://whop.com/blog/amazon-trends/',products:['Samyang Buldak Hot Chicken Ramen Variety','Hi-Chew Sensationally Chewy Fruit Candy','Korean Snack Box Variety Pack 40-Count']},
{t:'📈 趨勢',h:'植物基蛋白與素食食品持續成長，Flexitarian 飲食推動需求',p:'不完全素食的「彈性素食者」（Flexitarian）推動植物基蛋白粉、素肉、燕麥奶需求。Orgain 有機蛋白粉穩居 Best Seller。植物基起司與植物基優格也在成長。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Orgain Organic Plant Based Protein Powder','Oatly Oat Milk Barista Edition','Beyond Meat Plant-Based Burger Patties']},
{t:'📈 趨勢',h:'機能性飲料與電解質粉包取代傳統運動飲料',p:'消費者從含糖運動飲料轉向低糖/無糖電解質粉包。Liquid I.V. 與 LMNT 品牌在 Amazon 上銷量領先。「隨身包」形式方便攜帶，單包 $1-2 價位帶接受度高。健身族群與戶外運動者是主要客群。',src:'https://explodingtopics.com/blog/trending-products',products:['Liquid I.V. Hydration Multiplier','LMNT Zero-Sugar Electrolytes','Nuun Sport Electrolyte Drink Tablets']},
{t:'📈 趨勢',h:'有機與非 GMO 食品溢價空間大，USDA Organic 認證是關鍵',p:'消費者願意為 USDA Organic、Non-GMO Project Verified 認證食品多付 15-25%。有機堅果、有機蜂蜜、有機橄欖油是熱銷品。Amazon 自有品牌 365 by Whole Foods 也在搶佔市場。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['365 by Whole Foods Market Organic Raw Honey','Blue Diamond Almonds Whole Natural','California Olive Ranch Extra Virgin Olive Oil']},
{t:'📈 趨勢',h:'低糖/無糖零食需求上升，GLP-1 藥物使用者推動健康零食市場',p:'GLP-1 減重藥物（如 Ozempic）使用者增加，推動低糖、高蛋白、小份量零食需求。Quest Protein Chips、SmartSweets 低糖軟糖搜尋量年增 50%+。「Ozempic-friendly snacks」成為新搜尋關鍵字。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Quest Nutrition Protein Chips Variety Pack','SmartSweets Gummy Bears Low Sugar','Chomps Original Beef Jerky Sticks']},
{t:'📈 趨勢',h:'咖啡品類競爭激烈但市場龐大，冷萃濃縮液與風味糖漿成長快',p:'咖啡是 Amazon Grocery 最大子品類。冷萃濃縮液（Cold Brew Concentrate）讓消費者在家快速製作冰咖啡。風味糖漿（香草、焦糖、榛果）搜尋量年增 25%。咖啡訂閱回購率超過 70%。',src:'https://www.accio.com/business/grocery-items-food-best-sellers',products:['Chameleon Organic Cold-Brew Coffee Concentrate','Torani Variety Pack Flavoring Syrup','Lavazza Super Crema Whole Bean Coffee']},
{t:'📈 趨勢',h:'調味料與醬料禮盒組在節日季銷量翻倍，適合新賣家切入',p:'辣醬、BBQ 醬、異國調味料禮盒組在聖誕節、父親節銷量翻倍。$15-30 價位帶的禮盒組轉換率高。Variety Pack 形式讓消費者嘗試多種口味。客製化標籤與精美包裝是差異化關鍵。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Truff Hot Sauce Variety Pack','Fly By Jing Sichuan Chili Crisp','Mike\'s Hot Honey 10 oz Bottle']}
],
health:[
{t:'📈 趨勢',h:'益生菌、膠原蛋白、軟糖型保健品（Gummies）成長最快',p:'保健品需求持續爆發。SuperBeets 心臟保健軟糖等「低門檻健康習慣」產品受歡迎。軟糖型態（Gummies）是目前最受歡迎劑型。BNPL 佔訂單 8.1%，降低高單價保健品消費門檻。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['HumanN SuperBeets Heart Chews','Vital Proteins Collagen Peptides Powder','Culturelle Daily Probiotic Gummies']},
{t:'📈 趨勢',h:'睡眠輔助產品需求穩定成長，褪黑激素軟糖與白噪音機熱銷',p:'美國成人 35%+ 有睡眠問題，推動睡眠輔助產品需求。褪黑激素軟糖、鎂補充劑、白噪音機是三大熱銷品。加重毯（Weighted Blanket）銷量穩定。「Sleep Hygiene」成為社群熱門話題。',src:'https://explodingtopics.com/blog/trending-products',products:['Olly Sleep Melatonin Gummies','Natural Vitality Calm Magnesium Supplement','Hatch Restore 2 Sound Machine']},
{t:'📈 趨勢',h:'居家健康監測設備普及，血壓計與血氧機成為家庭必備',p:'COVID 後消費者更重視居家健康監測。血壓計、血氧機、體溫計銷量穩定。智慧體重計（連接 App 追蹤趨勢）搜尋量年增 20%。Withings 與 Omron 品牌在 Amazon 上領先。',src:'https://www.accio.com/business/amazon-best-selling-health',products:['Omron Platinum Blood Pressure Monitor','Withings Body+ Smart Scale','Masimo MightySat Finger Pulse Oximeter']},
{t:'📈 趨勢',h:'腸道健康成為保健新焦點，益生菌與發酵食品補充劑需求上升',p:'「Gut Health」成為 2026 年保健最熱門關鍵字。益生菌、益生元、消化酵素搜尋量年增 30%。Seed DS-01 與 Athletic Greens（AG1）在社群上獲得大量推薦。腸道健康與免疫力、心理健康的關聯研究推動需求。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Seed DS-01 Daily Synbiotic','AG1 Athletic Greens Powder','Garden of Life Raw Probiotics Ultimate Care']},
{t:'📈 趨勢',h:'女性健康保健品市場快速成長，經期舒緩與更年期產品需求上升',p:'女性健康保健品從小眾走向主流。經期舒緩軟糖、更年期補充劑、孕期維他命搜尋量年增 25%。Ritual 與 Olly 品牌以時尚包裝與透明成分吸引年輕女性消費者。',src:'https://whop.com/blog/amazon-trends/',products:['Ritual Essential Prenatal Multivitamin','Olly Happy Hoo-Ha Probiotic','MegaFood Baby & Me 2 Prenatal Vitamin']},
{t:'📈 趨勢',h:'運動恢復與肌肉放鬆產品需求上升，筋膜槍與按摩球熱銷',p:'健身人口增加推動運動恢復產品需求。筋膜槍（Massage Gun）、泡棉滾筒、按摩球搜尋量穩定。Theragun 與 Hyperice 品牌主導高端市場，$50-100 平價替代品銷量更大。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Theragun Relief Massage Gun','TriggerPoint GRID Foam Roller','OPTP Pro-Roller Soft Density Foam Roller']},
{t:'📈 趨勢',h:'口腔保健產品升級，電動牙刷與牙齒美白產品持續熱銷',p:'消費者從手動牙刷升級到電動牙刷。Oral-B 與 Philips Sonicare 穩居 Best Seller。牙齒美白貼片、美白牙膏搜尋量年增 20%。牙線棒與沖牙機也在成長。',src:'https://supplykick.com/blog/amazon-health-trends',products:['Oral-B iO Series 9 Electric Toothbrush','Crest 3D Whitestrips Professional Effects','Waterpik Aquarius Water Flosser']},
{t:'📈 趨勢',h:'急救與居家醫療用品是全年穩定需求品項，Bundle 組合銷售效果好',p:'急救包、OK 繃、醫療膠帶等基礎醫療用品全年需求穩定。家庭急救包在颶風季（Q3）與流感季（Q4）銷量上升。Bundle 組合（急救包+體溫計+血壓計）轉換率高於單品。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Johnson & Johnson All-Purpose First Aid Kit','Band-Aid Brand Flexible Fabric Bandages','Braun ThermoScan 7 Ear Thermometer']}
],

pet:[
{t:'📈 趨勢',h:'Pet Day 首次擴展至 5 天，寵物人性化驅動高附加價值產品需求',p:'美國寵物市場 $1,570 億，94M 家庭擁有寵物。Amazon Pet Day 2026 擴展至 5/11-15（5 天）。益智玩具、舔食墊、凍乾零食是三大爆品方向。天然成分、關節保健、腸胃益生菌是消費者首選。Top 5 品牌：Amazon Basics、Milk-Bone、Earth Rated、Greenies、Blue Buffalo。',src:'https://www.accio.com/business/best-seller-for-pet-amazon',products:['Outward Hound Nina Ottosson Puzzle Toy','MateeyLife Lick Mat for Dogs (2-Pack)','Stella & Chewy\'s Freeze-Dried Raw Dinner Patties']},
{t:'📈 趨勢',h:'寵物保健品市場快速成長，關節保健與焦慮舒緩是兩大方向',p:'寵物主人願意為毛孩健康投資。關節保健（葡萄糖胺）、焦慮舒緩（CBD 替代品）、皮膚毛髮保健（魚油）是三大熱銷保健品方向。軟嚼型態（Soft Chews）最受歡迎。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Zesty Paws Mobility Bites Hip & Joint','PetHonesty Calming Hemp Chews','Zesty Paws Pure Wild Alaskan Salmon Oil']},
{t:'📈 趨勢',h:'智慧寵物用品從新奇變實用，自動餵食器與 GPS 追蹤器需求上升',p:'WiFi 自動餵食器、寵物攝影機、GPS 追蹤項圈搜尋量年增 25%。上班族與旅行者是主要客群。App 控制與 Alexa 整合是重要賣點。$30-80 價位帶入門款銷量最高。',src:'https://whop.com/blog/amazon-trends/',products:['PETLIBRO Automatic Cat Feeder WiFi','Furbo 360° Dog Camera','Apple AirTag for Pet Collar']},
{t:'📈 趨勢',h:'貓用品市場成長快於狗用品，貓砂與貓抓板是最大子品類',p:'美國貓飼養數量超過狗，推動貓用品市場快速成長。豆腐貓砂（環保可沖馬桶）搜尋量年增 40%。貓抓板、貓隧道、貓草玩具是穩定需求品項。自動貓砂盆是高單價成長品類。',src:'https://explodingtopics.com/blog/trending-products',products:['pidan Original Tofu Cat Litter','PetFusion Ultimate Cat Scratcher Lounge','Litter-Robot 4 Automatic Self-Cleaning Litter Box']},
{t:'📈 趨勢',h:'寵物服飾與配件成為社群分享熱點，萬聖節與聖誕節銷量翻倍',p:'寵物服飾在社群上傳播力強。萬聖節寵物裝扮、聖誕節寵物毛衣、生日派對帽搜尋量在節日前 4-6 週爆發。日常款（雨衣、保暖背心）全年穩定銷售。$10-20 價位帶最受歡迎。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Rubie\'s Pet Halloween Costume','Gooby Fleece Dog Vest','BINGPET Dog Birthday Bandana']},
{t:'📈 趨勢',h:'天然與有機寵物食品需求上升，消費者閱讀成分標籤更仔細',p:'寵物主人對寵物食品成分越來越謹慎。無穀物、限定成分、人類等級（Human-Grade）食品搜尋量年增 30%。The Farmer\'s Dog 與 Ollie 等新鮮寵物食品品牌帶動趨勢。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Blue Buffalo Life Protection Formula','Wellness CORE Grain-Free Dog Food','Open Farm Homestead Turkey Dog Food']},
{t:'📈 趨勢',h:'寵物清潔與美容用品需求穩定，DIY 居家美容取代寵物沙龍',p:'寵物美容沙龍費用上漲推動 DIY 居家美容需求。寵物電動剃毛器、寵物吹水機、寵物洗澡手套搜尋量年增 20%。寵物專用洗毛精（天然成分、低敏配方）是高回購品項。',src:'https://supplykick.com/blog/amazon-pet-trends',products:['oneisall Dog Clippers Low Noise','Aquapaw Pet Bathing Tool','Burt\'s Bees for Dogs Natural Shampoo']},
{t:'📈 趨勢',h:'寵物旅行用品需求上升，航空公司核准寵物提袋與車用配件熱銷',p:'旅遊復甦推動寵物旅行用品需求。航空公司核准尺寸的寵物提袋、可摺疊寵物碗、寵物護照夾搜尋量年增 25%。車用寵物安全座椅與後座保護墊也在成長。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Sherpa Original Deluxe Airline Approved Pet Carrier','Ruffwear Quencher Collapsible Dog Bowl','PetSafe Happy Ride Dog Safety Harness']},
{t:'📈 趨勢',h:'Subscribe & Save 在寵物品類滲透率最高，貓砂與飼料訂閱回購率超過 75%',p:'寵物品類是 Amazon Subscribe & Save 滲透率最高的品類之一。貓砂、乾飼料、零食訂閱回購率超過 75%。品牌透過訂閱折扣（5-15%）鎖定長期客戶。訂閱制降低價格敏感度。',src:'https://helium10.com/blog/amazon-pet-trends',products:['Purina ONE SmartBlend Dog Food','Fresh Step Clean Paws Cat Litter','Greenies Original Dental Dog Treats']}
],
sports:[
{t:'📈 趨勢',h:'居家健身長青熱銷，Pickleball 成為 2026 運動品類黑馬',p:'阻力帶、瑜珈墊、可調式啞鈴是長青品。$50 以下「essential luxury」最受歡迎。Pickleball（匹克球）相關裝備是 2026 年黑馬，搜尋量與銷量快速成長。輕量化露營裝備需求穩定。',src:'https://whop.com/blog/amazon-trends/',products:['Fit Simplify Resistance Loop Bands Set','JOOLA Ben Johns Hyperion Pickleball Paddle','Manduka PRO Yoga Mat']},
{t:'📈 趨勢',h:'跑步與馬拉松熱潮推動跑步配件需求，GPS 手錶與能量膠熱銷',p:'美國馬拉松參賽人數創新高，推動跑步配件需求。GPS 運動手錶、跑步腰包、能量膠/能量棒搜尋量年增 20%。Garmin 與 COROS 品牌在 Amazon 上銷量領先。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Garmin Forerunner 265 GPS Running Watch','FlipBelt Running Belt','GU Energy Original Sports Nutrition Gel']},
{t:'📈 趨勢',h:'瑜珈與冥想用品持續成長，瑜珈磚與冥想坐墊是穩定需求品',p:'瑜珈與冥想從運動延伸為生活方式。瑜珈磚、瑜珈繩、冥想坐墊、瑜珈輪搜尋量穩定。Cork（軟木）材質瑜珈磚因環保特性受歡迎。$10-30 價位帶入門用品最受歡迎。',src:'https://www.accio.com/business/amazon-best-selling-sports',products:['Manduka Cork Yoga Block 2-Pack','Gaiam Meditation Cushion','UpCircleSeven Yoga Wheel']},
{t:'📈 趨勢',h:'露營與戶外裝備需求穩定，輕量化與多功能設計是關鍵賣點',p:'露營從疫情期間的爆發轉為穩定需求。輕量化帳篷、便攜式爐具、多功能工具刀是熱銷品。「Glamping」（豪華露營）推動高品質露營用品需求。Q2-Q3 是銷售高峰。',src:'https://explodingtopics.com/blog/trending-products',products:['Coleman Sundome Camping Tent 4-Person','Jetboil Flash Camping Stove','Leatherman FREE P4 Multitool']},
{t:'📈 趨勢',h:'游泳與水上運動配件在夏季銷量翻倍，防水手機袋是意外爆品',p:'游泳鏡、浮板、防水手機袋在 Q2-Q3 銷量翻倍。防水手機袋（$8-15）是高利潤衝動購買品。充氣式 SUP（Stand Up Paddle）板搜尋量年增 25%。提前至 Q1 備貨是關鍵。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Speedo Vanquisher 2.0 Swim Goggles','JOTO Universal Waterproof Phone Pouch','SereneLife Inflatable Stand Up Paddle Board']},
{t:'📈 趨勢',h:'高爾夫配件市場穩定成長，練習網與 GPS 測距儀受業餘球友歡迎',p:'高爾夫參與人數在疫情後維持高位。居家練習網、推桿練習墊、GPS 測距儀搜尋量穩定。$50-150 價位帶的練習裝備最受業餘球友歡迎。高爾夫手套與球標是低單價高回購品。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['GoSports Golf Practice Hitting Net','Callaway 300 Pro Laser Rangefinder','SKLZ Accelerator Pro Indoor Putting Green']},
{t:'📈 趨勢',h:'智慧健身追蹤配件需求上升，心率帶與智慧跳繩成為新寵',p:'消費者追求數據化健身體驗。藍牙心率帶、智慧跳繩（計數+卡路里）、智慧水壺（追蹤飲水量）搜尋量年增 30%。與 Apple Health、Strava 等 App 整合是重要賣點。',src:'https://helium10.com/blog/amazon-fitness-trends',products:['Polar H10 Heart Rate Monitor Chest Strap','Tangram Smart Rope LED Jump Rope','HidrateSpark PRO Smart Water Bottle']},
{t:'📈 趨勢',h:'女性運動用品市場快速成長，運動內衣與瑜珈褲是最大子品類',p:'女性運動參與率持續提升，推動女性專用運動用品需求。運動內衣、高腰瑜珈褲、運動髮帶是熱銷品。Lululemon 平價替代品在 Amazon 上銷量驚人。$15-35 價位帶成長最快。',src:'https://backlinko.com/ecommerce-stats',products:['CRZ YOGA Butterluxe High Waisted Leggings','Lemedy Women Padded Sports Bra','Maven Thread Workout Headbands 5-Pack']}
],
apparel:[
{t:'📈 趨勢',h:'Amazon Essentials 自有品牌強勢，永續時尚與機能服飾需求上升',p:'消費者偏好高 CP 值基本款。Amazon 自有品牌市佔率持續提升。使用回收材質、有機棉的品牌獲得更高曝光。Climate Pledge Friendly 標章加分。機能服飾（吸濕排汗、抗UV）跨界日常穿搭。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Amazon Essentials Men\'s Slim-Fit T-Shirt','Hanes EcoSmart Fleece Sweatshirt','CRZ YOGA Butterluxe High Waisted Leggings']},
{t:'📈 趨勢',h:'Athleisure 運動休閒風持續主導，瑜珈褲與慢跑褲成為日常穿搭',p:'運動休閒風（Athleisure）從趨勢變為常態。瑜珈褲、慢跑褲、運動外套成為日常穿搭。消費者追求「從健身房到咖啡廳」的多場景穿搭。$20-40 價位帶的平價替代品銷量最大。',src:'https://whop.com/blog/amazon-trends/',products:['Colorfulkoala Women\'s High Waisted Joggers','THE GYM PEOPLE Thick High Waist Yoga Pants','Baleaf Women\'s Fleece Lined Leggings']},
{t:'📈 趨勢',h:'大尺碼與包容性尺寸需求上升，品牌擴展尺碼範圍成為趨勢',p:'消費者要求更多尺碼選擇。提供 XS-4XL 完整尺碼範圍的品牌獲得更高評價。大尺碼泳裝、大尺碼運動服搜尋量年增 25%。包容性行銷（多元體型模特兒）提升品牌好感度。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['JUST MY SIZE Plus Size T-Shirt','Hanna Nikole Plus Size Swim Dress','Gloria Vanderbilt Amanda Classic Tapered Jean']},
{t:'📈 趨勢',h:'UPF 防曬服飾從戶外專用走向日常穿搭，搜尋量年增 35%',p:'皮膚癌意識提升推動 UPF 防曬服飾需求。UPF 50+ 長袖上衣、防曬帽、防曬袖套從戶外運動延伸到日常穿搭。Coolibar 與 Columbia 品牌在 Amazon 上領先。夏季銷量翻倍。',src:'https://explodingtopics.com/blog/trending-products',products:['Coolibar UPF 50+ Women\'s Long Sleeve Shirt','Columbia Bora Bora Booney Sun Hat','UV Protection Arm Sleeves 4-Pairs']},
{t:'📈 趨勢',h:'內衣與貼身衣物線上購買比例持續提升，無痕內衣成為主流',p:'消費者越來越習慣線上購買內衣。無痕內衣、無鋼圈胸罩、竹纖維內褲搜尋量年增 20%。尺寸指南與退換貨政策是消費者選購的關鍵考量。Subscribe & Save 在襪子品類滲透率高。',src:'https://www.accio.com/business/amazon-best-selling-apparel',products:['Warner\'s Cloud 9 Wireless Bra','Fruit of the Loom Women\'s Seamless Panties','Bombas Men\'s Ankle Socks 4-Pack']},
{t:'📈 趨勢',h:'工作服與制服市場穩定，醫療護理人員工作服（Scrubs）是熱門品項',p:'醫療護理人員工作服（Scrubs）在 Amazon 上銷量穩定。FIGS 品牌以時尚設計顛覆傳統工作服市場。餐飲業圍裙、建築業安全背心等職業服飾也有穩定需求。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['FIGS Catarina Scrub Top','Dickies EDS Signature Scrub Pants','Hudson Durable Goods Professional Chef Apron']},
{t:'📈 趨勢',h:'季節性服飾需求明顯，提前 6-8 週備貨是關鍵',p:'服飾品類季節性極強。泳裝（Q1 備貨）、秋冬外套（Q3 備貨）、節日派對服（Q4 備貨）需提前 6-8 週準備。Prime Day（7月）與 Black Friday（11月）是兩大折扣季。',src:'https://junglescout.com/blog/amazon-seasonal-trends/',products:['Dokotoo Women\'s One Piece Swimsuit','Amazon Essentials Women\'s Puffer Jacket','GRACE KARIN Sequin Cocktail Dress']},
{t:'📈 趨勢',h:'復古與 Y2K 風格回歸，寬褲與 Oversized 上衣受 Gen Z 歡迎',p:'Gen Z 推動 Y2K（2000 年代）風格回歸。寬褲、Oversized 上衣、低腰牛仔褲搜尋量年增 30%。Vintage 風格圖案 T-shirt 與復古運動外套也受歡迎。TikTok #OOTD 帶動流量。',src:'https://backlinko.com/ecommerce-stats',products:['Levi\'s Women\'s Ribcage Wide Leg Jeans','Hanes Beefy-T Oversized T-Shirt','Adidas Originals Adicolor Classics Track Jacket']}
],
jewelry:[
{t:'📈 趨勢',h:'平價極簡飾品（$10-30）銷量驚人，個性化客製需求上升',p:'不鏽鋼/鍍金極簡飾品、疊戴手鍊、刻字項鍊是熱銷品。個性化飾品（生日石、星座主題）在禮品場景（生日、母親節）季節性爆發。低單價高回購率。',src:'https://salesduo.com/blog/amazon-statistics/',products:['PAVOI 14K Gold Plated Huggie Earrings','Personalized Name Necklace Sterling Silver','MVMT Women\'s Minimalist Watch']},
{t:'📈 趨勢',h:'Lab-Grown Diamond（實驗室培育鑽石）搜尋量暴增，價格優勢吸引年輕消費者',p:'Lab-Grown Diamond 價格僅天然鑽石 30-40%，吸引 Millennial 與 Gen Z 消費者。訂婚戒指、耳環、項鍊搜尋量年增 50%+。環保與倫理訴求也是購買動機。',src:'https://explodingtopics.com/blog/trending-products',products:['PAVOI 14K Gold Lab-Grown Diamond Studs','Helzberg Diamonds Lab-Grown Diamond Ring','Brilliant Earth Lab-Grown Diamond Pendant']},
{t:'📈 趨勢',h:'男性飾品市場快速成長，串珠手鍊與極簡戒指受歡迎',p:'男性飾品從小眾走向主流。串珠手鍊、極簡鈦鋼戒指、皮革手環搜尋量年增 25%。社群媒體上「男士穿搭配件」內容帶動需求。$10-25 價位帶最受歡迎。',src:'https://whop.com/blog/amazon-trends/',products:['FIBO STEEL Stainless Steel Bracelets for Men','TUNGSTEN CARBIDE Men\'s Wedding Band','Fossil Men\'s Minimalist Watch']},
{t:'📈 趨勢',h:'防水與抗過敏飾品需求上升，不鏽鋼與鈦金屬取代傳統合金',p:'消費者對飾品過敏問題關注度提升。316L 不鏽鋼、鈦金屬、純銀飾品標榜「防水、抗過敏、不褪色」獲得更高評價。「Tarnish-free」成為重要搜尋關鍵字。',src:'https://www.accio.com/business/amazon-best-selling-jewelry',products:['PAVOI 14K Gold Plated Tarnish-Free Earrings','PROSTEEL Stainless Steel Cuban Link Chain','Miabella 925 Sterling Silver Italian Chain']},
{t:'📈 趨勢',h:'飾品收納與展示用品是高利潤搭配品項',p:'消費者購買飾品後需要收納解決方案。旅行飾品盒、首飾展示架、耳環收納板搜尋量穩定。$10-25 價位帶的飾品收納用品利潤率高。「經常一起購買」推薦帶動銷量。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['SONGMICS Jewelry Box Organizer','ProCase Travel Jewelry Case','Angelynn\'s Earring Holder Organizer']},
{t:'📈 趨勢',h:'母親節與情人節是飾品品類最大銷售季，提前 4 週備貨',p:'母親節（5月）與情人節（2月）是飾品品類兩大銷售高峰，銷量可達平日 5-8 倍。心形項鍊、生日石戒指、「Mom」主題飾品在母親節前 4 週搜尋量暴增。禮盒包裝是必備。',src:'https://junglescout.com/blog/amazon-seasonal-trends/',products:['PAVOI Heart Necklace for Mom','Alex and Ani Birthstone Bangle','Pandora Moments Heart Clasp Bracelet']},
{t:'📈 趨勢',h:'智慧戒指與科技飾品成為新興品類，Oura Ring 帶動趨勢',p:'Oura Ring 等智慧戒指將健康追蹤融入飾品。智慧戒指配件（充電座、保護殼）在 Amazon 上銷量成長。NFC 智慧戒指（可儲存名片、支付）也在萌芽階段。',src:'https://helium10.com/blog/amazon-jewelry-trends',products:['Oura Ring Gen 3 Heritage','CNICK Smart NFC Ring','Oura Ring Charging Dock']},
{t:'📈 趨勢',h:'疊戴風格（Layering）持續流行，多件組合套裝銷量高於單品',p:'消費者偏好購買可疊戴的飾品組合。3-5 件套裝項鍊、疊戴戒指組、混搭耳環組銷量高於單品。套裝定價（$15-30）比單品更有吸引力。社群上「疊戴教學」內容帶動需求。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['PAVOI Layered Necklace Set 3-Pack','FIBO STEEL Stackable Rings Set','Adoyi Gold Hoop Earrings Set 6-Pairs']}
],

shoes:[
{t:'📈 趨勢',h:'舒適鞋款與旅行收納配件持續熱銷，旅遊復甦帶動行李箱需求',p:'記憶棉鞋墊、輕量化休閒鞋持續熱銷。旅遊復甦推動輕量化登機箱、旅行收納套組、防盜背包搜尋量上升。$40-80 價位帶成長最快。TSA 鎖是美國市場必備功能。',src:'https://www.clickpost.ai/blog/online-shopping-categories',products:['Samsonite Freeform Hardside Carry-On','BAGSMART Travel Packing Cubes Set','Skechers Go Walk Joy Slip-On Sneaker']},
{t:'📈 趨勢',h:'雲朵鞋（Cloud Shoes）與厚底鞋持續熱銷，舒適度成為首要考量',p:'On Cloud 與 Hoka 帶動「雲朵鞋」風潮。厚底、緩震、輕量化是消費者三大需求。Amazon 上平價替代品（$30-60）銷量驚人。護理師、教師等久站職業是重要客群。',src:'https://explodingtopics.com/blog/trending-products',products:['On Cloud 5 Running Shoe','Hoka Bondi 8 Running Shoe','Skechers Arch Fit Slip-On Sneaker']},
{t:'📈 趨勢',h:'拖鞋與居家鞋成為全年穩定需求品，記憶棉材質最受歡迎',p:'遠端工作推動居家拖鞋需求常態化。記憶棉拖鞋、羊毛拖鞋、防滑室內鞋搜尋量穩定。$15-30 價位帶銷量最高。冬季銷量翻倍。禮品場景（聖誕節）也推動銷量。',src:'https://whop.com/blog/amazon-trends/',products:['Dearfoams Women\'s Memory Foam Slippers','ULTRAIDEAS Men\'s Cozy Memory Foam Slippers','Crocs Classic Lined Clog']},
{t:'📈 趨勢',h:'兒童鞋市場穩定成長，易穿脫設計與發光鞋是熱門品項',p:'兒童鞋需求穩定（孩子腳快速成長需頻繁更換）。魔鬼氈易穿脫設計、LED 發光鞋、防水雨靴是熱門品項。$20-40 價位帶最受歡迎。Back-to-School 季節（Q3）銷量上升。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Skechers Kids S Lights Sneaker','Native Jefferson Kids Slip-On','KEEN Kids Newport H2 Sandal']},
{t:'📈 趨勢',h:'鞋墊與鞋類配件利潤率高，足弓支撐鞋墊是長青熱銷品',p:'足弓支撐鞋墊、增高鞋墊、除臭鞋墊是全年穩定需求品。$10-20 價位帶衝動購買率高。足底筋膜炎患者是重要客群。「經常一起購買」推薦帶動鞋墊與鞋款搭配銷售。',src:'https://www.accio.com/business/amazon-best-selling-shoes',products:['Dr. Scholl\'s Heavy Duty Support Insoles','Superfeet GREEN Insoles','Arm & Hammer Shoe Odor Insoles']},
{t:'📈 趨勢',h:'防水與戶外鞋款在秋冬季銷量上升，Gore-Tex 材質是賣點',p:'秋冬季推動防水靴、雪靴、防滑鞋需求。Gore-Tex 防水透氣材質是消費者首選。Merrell、Columbia、Timberland 品牌在 Amazon 上銷量領先。$60-120 價位帶成長最快。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Merrell Moab 3 Waterproof Hiking Shoe','Columbia Newton Ridge Plus Waterproof Boot','Timberland 6 Inch Premium Waterproof Boot']},
{t:'📈 趨勢',h:'涼鞋與水鞋在 Q2-Q3 季節性爆發，Birkenstock 替代品銷量驚人',p:'Birkenstock 風格涼鞋的平價替代品在 Amazon 上銷量驚人。水鞋（Water Shoes）在夏季搜尋量翻倍。$15-35 價位帶最受歡迎。提前至 Q1 備貨是關鍵策略。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Arizona Soft Footbed Sandal (Birkenstock Style)','SIMARI Water Shoes Quick-Dry','Teva Original Universal Sandal']},
{t:'📈 趨勢',h:'永續鞋款需求上升，回收材質與環保品牌獲得更高關注',p:'消費者對鞋類永續性關注度提升。使用回收塑膠瓶、天然橡膠、有機棉的鞋款獲得更高評價。Allbirds 與 Veja 等環保品牌帶動趨勢。Climate Pledge Friendly 標章提升曝光率。',src:'https://supplykick.com/blog/amazon-shoes-trends',products:['Allbirds Wool Runners','Veja Campo Sneaker','Cariuma IBI Low-Top Sneaker']},
{t:'📈 趨勢',h:'鞋類尺寸與合腳度是最大退貨原因，詳細尺寸指南降低退貨率',p:'鞋類是 Amazon 退貨率最高的品類之一（約 30%）。提供詳細尺寸對照表、寬楦/窄楦選項、真實穿著照片的賣家退貨率顯著降低。Virtual Try-On 功能正在測試中。',src:'https://backlinko.com/ecommerce-stats',products:['New Balance 574 Core Sneaker','ASICS Gel-Kayano 30 Running Shoe','Brooks Ghost 15 Running Shoe']}
],
toys:[
{t:'📈 趨勢',h:'STEM 教育玩具主導，感官玩具穩定需求，Q4 是最大銷售季',p:'家長偏好有教育意義的玩具。程式學習機器人、科學實驗套組、策略桌遊是熱門品項。感官刺激玩具（Sensory Toys）持續有穩定需求。戶外泡泡機、水槍等 Q2-Q3 季節性爆發。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['LEGO Education SPIKE Essential Set','National Geographic Mega Science Kit','Pop It Fidget Sensory Toy Pack']},
{t:'📈 趨勢',h:'桌遊與家庭遊戲復興，策略型桌遊成長快於傳統派對遊戲',p:'家庭遊戲之夜（Game Night）文化推動桌遊銷量。策略型桌遊（如 Wingspan、Azul）成長快於傳統派對遊戲。$20-40 價位帶最受歡迎。TikTok #BoardGameTok 帶動新玩家入門。',src:'https://whop.com/blog/amazon-trends/',products:['Wingspan Board Game','Azul Board Game','Codenames Party Game']},
{t:'📈 趨勢',h:'戶外玩具在 Q2-Q3 季節性爆發，泡泡機與水槍是夏季爆品',p:'泡泡機、水槍、充氣泳池在夏季銷量可達冬季 10 倍。提前至 Q1 備貨至關重要。$10-25 價位帶衝動購買率最高。戶外遊樂設備（鞦韆、滑梯）在春季搜尋量上升。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Gazillion Bubbles Machine','Super Soaker XP100 Water Blaster','Intex Rectangular Above Ground Pool']},
{t:'📈 趨勢',h:'收藏型玩具（Collectibles）持續熱銷，盲盒與交換卡牌驅動回購',p:'Squishmallows、Pokémon 卡牌、Mini Brands 盲盒持續熱銷。收藏型玩具的回購率遠高於一般玩具。限量版與稀有款推動二手市場溢價。社群上的「開箱」影片帶動購買。',src:'https://explodingtopics.com/blog/trending-products',products:['Squishmallows 12-Inch Plush','Pokémon TCG Booster Bundle','5 Surprise Mini Brands Series 5']},
{t:'📈 趨勢',h:'建構型玩具（LEGO、磁力片）是家長最願意投資的品類',p:'LEGO 穩居 Amazon Toys #1 品牌。磁力片（Magna-Tiles）、積木、拼圖等建構型玩具被視為「有教育價值的投資」。家長願意為建構型玩具支付更高價格。$30-80 價位帶成長最快。',src:'https://www.accio.com/business/amazon-best-selling-toys',products:['LEGO Classic Large Creative Brick Box','Magna-Tiles Clear Colors 100-Piece Set','Melissa & Doug Wooden Building Blocks']},
{t:'📈 趨勢',h:'嬰幼兒玩具（0-3 歲）需求穩定，安全認證是首要考量',p:'嬰幼兒玩具全年需求穩定。ASTM F963 安全認證、BPA-free、無小零件是家長首要考量。布書、堆疊杯、感官球是熱門品項。Baby Shower 禮品場景推動銷量。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Baby Einstein Take Along Tunes Musical Toy','Fisher-Price Rock-a-Stack','Manhattan Toy Winkel Rattle & Sensory Teether']},
{t:'📈 趨勢',h:'遙控車與無人機受男孩歡迎，入門級無人機（$30-60）銷量成長快',p:'遙控車、遙控飛機、入門級無人機是男孩最受歡迎的禮物。$30-60 價位帶入門級無人機銷量成長最快。附帶攝影機的款式更受歡迎。聖誕節與生日是主要銷售時機。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Holy Stone HS110D FPV Drone with Camera','Traxxas Slash 2WD RC Truck','DEERC D20 Mini Drone for Kids']},
{t:'📈 趨勢',h:'角色扮演與裝扮玩具受女孩歡迎，Disney 授權產品穩居熱銷',p:'Disney 公主裝扮、廚房扮家家酒、醫生工具組是女孩熱門玩具。Disney 新電影上映會帶動相關角色商品銷量。萬聖節是裝扮玩具最大銷售季。$15-35 價位帶最受歡迎。',src:'https://helium10.com/blog/amazon-toys-trends',products:['Disney Princess Dress Up Trunk','Melissa & Doug Star Diner Restaurant Play Set','LeapFrog Learning Friends 100 Words Book']},
{t:'📈 趨勢',h:'Q4 佔玩具品類全年銷量 40%+，Black Friday 到聖誕節是決戰期',p:'玩具品類季節性極強，Q4（10-12月）佔全年銷量 40%+。Amazon Holiday Toy List 是重要曝光管道。提前至 Q3 備貨、設定 Lightning Deal 是關鍵策略。1月清倉期也有銷售機會。',src:'https://supplykick.com/blog/amazon-toys-trends',products:['Barbie Dreamhouse 2024','Hot Wheels Ultimate Garage Playset','Nintendo Switch Game & Watch']}
],

electronics:[
{t:'📈 趨勢',h:'GaN 充電器與 USB-C Hub 穩居 Best Seller，AI 配件市場正在形成',p:'Anker 65W GaN 充電器是 2026 全球第二暢銷品。USB-C 統一趨勢推動轉接器、Hub、線材需求。Electronics 佔 Amazon 搜尋量 24%。Qi2 無線充電標準正在取代舊版 Qi。AI Pin、AI 眼鏡帶動周邊配件新品類。',src:'https://www.alibaba.com/product-insights/top-amazon-best-selling-products-2026-market-trends-regional-breakdown-and-strategic-insights.html',products:['Anker Prime 65W GaN Wall Charger 3-Port','UGREEN 100W USB-C 4-Port GaN Charger','Anker 341 USB-C Hub 7-in-1']},
{t:'📈 趨勢',h:'行動電源需求穩定，大容量與快充成為標配',p:'20000mAh+ 大容量行動電源搜尋量穩定。USB-C PD 快充（65W+）成為消費者基本要求。MagSafe 磁吸行動電源受 iPhone 用戶歡迎。$20-40 價位帶銷量最高。旅行與戶外場景推動需求。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Anker 737 Power Bank 24000mAh','Baseus MagSafe Portable Charger 10000mAh','INIU Portable Charger 22.5W Fast Charging']},
{t:'📈 趨勢',h:'智慧家居入門設備持續熱銷，Echo Dot 與智慧燈泡是最常見起點',p:'消費者通常從 Echo Dot 或智慧燈泡開始建構智慧家居。Amazon Echo 系列穩居 Electronics Best Seller。智慧插座、智慧門鈴、智慧攝影機是第二步購買品項。Prime Day 折扣推動大量首次購買。',src:'https://www.accio.com/business/amazon-best-selling-electronics',products:['Echo Dot 5th Gen Smart Speaker','Amazon Fire TV Stick 4K Max','Ring Indoor Cam 2nd Gen']},
{t:'📈 趨勢',h:'USB-C 統一趨勢推動線材與轉接器需求，歐盟法規加速轉型',p:'歐盟 USB-C 統一充電法規推動全球轉型。USB-C to Lightning 轉接器、USB-C Hub、USB-C 延長線搜尋量年增 30%。消費者更換舊設備時需要大量轉接配件。線材品質（編織線、快充認證）成為差異化關鍵。',src:'https://explodingtopics.com/blog/trending-products',products:['Anker USB-C to Lightning Cable 2-Pack','UGREEN USB-C Hub 6-in-1','Belkin USB-C to USB-C Cable 100W']},
{t:'📈 趨勢',h:'電子閱讀器與平板配件穩定銷售，Kindle 保護殼是長青品',p:'Kindle 保護殼、iPad 保護殼、平板支架是全年穩定需求品。新款 Kindle/iPad 發布後配件銷量會在 2-4 週內爆發。$10-25 價位帶的保護殼銷量最高。客製化設計是差異化方向。',src:'https://whop.com/blog/amazon-trends/',products:['Fintie Kindle Paperwhite Case','ESR iPad Air Case with Pencil Holder','Lamicall Adjustable Tablet Stand']},
{t:'📈 趨勢',h:'太陽能充電設備需求上升，戶外與緊急備用場景推動成長',p:'露營、健行、緊急備用場景推動太陽能充電板需求。可摺疊太陽能板（20W-100W）搜尋量年增 25%。搭配行動電源的太陽能充電套組銷量最高。Jackery 與 Goal Zero 品牌在 Amazon 上領先。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Jackery SolarSaga 100W Portable Solar Panel','Goal Zero Nomad 20 Solar Panel','BigBlue 28W Solar Charger']},
{t:'📈 趨勢',h:'螢幕保護貼與手機殼是 Electronics 最大子品類之一，新機發布帶動換購潮',p:'每年 iPhone/Samsung 新機發布帶動螢幕保護貼與手機殼換購潮。Spigen、OtterBox、TORRAS 品牌在 Amazon 上領先。$8-20 價位帶銷量最高。MagSafe 相容性成為 iPhone 殼必備功能。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Spigen Tough Armor iPhone 16 Pro Case','amFilm Tempered Glass Screen Protector','OtterBox Defender Series iPhone Case']},
{t:'📈 趨勢',h:'藍牙追蹤器需求穩定，AirTag 配件生態系持續擴張',p:'Apple AirTag 帶動藍牙追蹤器品類成長。AirTag 保護殼、鑰匙圈、寵物項圈掛件、行李牌等配件銷量穩定。Tile 品牌提供 Android 用戶替代方案。$5-15 配件利潤率高。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Apple AirTag 4-Pack','Belkin Secure Holder with Key Ring for AirTag','Tile Mate Bluetooth Tracker']},
{t:'📈 趨勢',h:'復古遊戲機與懷舊電子產品受 Millennial 歡迎',p:'復古遊戲機（NES/SNES Mini、Game Boy 風格掌機）受 Millennial 懷舊情感驅動。Anbernic 與 Miyoo 品牌的復古掌機在 Amazon 上銷量成長。$30-80 價位帶最受歡迎。禮品場景推動銷量。',src:'https://helium10.com/blog/amazon-electronics-trends',products:['Anbernic RG35XX Plus Retro Handheld','Miyoo Mini Plus Portable Game Console','8Bitdo Pro 2 Bluetooth Controller']}
],
camera:[
{t:'📈 趨勢',h:'創作者經濟推動補光燈、麥克風、穩定器需求，手機攝影配件超越傳統相機',p:'YouTube/TikTok/Podcast 創作者推動配件需求持續成長。手機鏡頭套組、手機穩定器、手機用 ND 濾鏡等「手機攝影」配件成長快於傳統相機配件。Vlog 相關配件是成長最快子品類。',src:'https://whop.com/blog/amazon-trends/',products:['Logitech for Creators Litra Glow','Rode VideoMicro II Compact Microphone','DJI OM 7 Smartphone Gimbal']},
{t:'📈 趨勢',h:'環形補光燈持續熱銷，直播與視訊會議雙重需求推動',p:'環形補光燈從網紅專用變為視訊會議必備。10 吋與 18 吋是最受歡迎尺寸。附帶手機架與三腳架的套組銷量最高。$15-40 價位帶成長最快。RGB 彩色燈效版本也受歡迎。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Neewer 18-inch Ring Light Kit','UBeesize 10 inch Selfie Ring Light','Lume Cube Panel Mini LED Light']},
{t:'📈 趨勢',h:'Action Camera 市場穩定，GoPro 替代品（$50-100）銷量成長快',p:'GoPro 穩居 Action Camera #1 但平價替代品市場更大。$50-100 價位帶的 4K Action Camera 銷量年增 30%。防水、防震、WiFi 傳輸是基本要求。配件（自拍桿、胸帶、頭帶）利潤率高。',src:'https://explodingtopics.com/blog/trending-products',products:['GoPro HERO12 Black','AKASO Brave 7 LE Action Camera','Insta360 X4 360° Action Camera']},
{t:'📈 趨勢',h:'Webcam 需求從疫情爆發轉為穩定，4K 與自動對焦成為新標準',p:'遠端工作常態化讓 Webcam 成為穩定需求品。4K 解析度、自動對焦、自動光線調整成為消費者基本要求。Logitech 穩居品類 #1。$50-100 價位帶成長最快。',src:'https://www.accio.com/business/amazon-best-selling-camera',products:['Logitech C920x HD Pro Webcam','Logitech Brio 4K Ultra HD Webcam','Anker PowerConf C200 2K Webcam']},
{t:'📈 趨勢',h:'即時列印相機（Instax）受 Gen Z 歡迎，復古攝影體驗帶動需求',p:'Fujifilm Instax 系列即時列印相機受 Gen Z 歡迎。「實體照片」的復古體驗在數位時代反而成為賣點。底片是高利潤回購品項。Instax Mini 12 穩居 Amazon Camera Best Seller。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Fujifilm Instax Mini 12 Camera','Fujifilm Instax Mini Film 60-Pack','Polaroid Go Gen 2 Instant Camera']},
{t:'📈 趨勢',h:'相機包與收納配件是高利潤搭配品項，旅行攝影推動需求',p:'相機包、鏡頭收納袋、記憶卡收納盒是穩定需求品。旅行攝影推動輕量化相機背包需求。Peak Design 品牌以設計感在 Amazon 上獲得高評價。$20-60 價位帶最受歡迎。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Peak Design Everyday Backpack V2','Lowepro Adventura SH 140 III Camera Bag','ProGrade Digital SD Card Case']},
{t:'📈 趨勢',h:'無人機攝影從專業走向消費級，DJI Mini 系列主導入門市場',p:'DJI Mini 系列（249g 以下免註冊）主導消費級無人機市場。$300-500 價位帶成長最快。ND 濾鏡、額外電池、收納包等配件利潤率高。房地產攝影與旅行 Vlog 是主要使用場景。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['DJI Mini 4 Pro Fly More Combo','DJI Mini 3 Drone','Freewell ND Filter Set for DJI Mini']},
{t:'📈 趨勢',h:'記憶卡與儲存設備需求穩定，高速 SD 卡與 SSD 是攝影師必備',p:'4K/8K 影片拍攝推動高速記憶卡需求。V30/V60/V90 速度等級成為消費者選購標準。SanDisk 與 Samsung 品牌穩居 Best Seller。外接 SSD 作為影片備份方案也在成長。',src:'https://helium10.com/blog/amazon-camera-trends',products:['SanDisk Extreme PRO 128GB SD Card','Samsung PRO Plus 256GB microSD Card','SanDisk Professional 2TB Portable SSD']},
{t:'📈 趨勢',h:'三腳架與穩定器市場成熟，輕量化旅行三腳架是成長最快子品類',p:'碳纖維旅行三腳架（重量低於 3 磅）搜尋量年增 20%。手機用迷你三腳架銷量超過傳統相機三腳架。$20-50 價位帶的入門三腳架銷量最高。Joby GorillaPod 穩居柔性三腳架 #1。',src:'https://supplykick.com/blog/amazon-camera-trends',products:['Joby GorillaPod 3K Kit','Peak Design Travel Tripod Carbon Fiber','UBeesize 67 inch Phone Tripod']}
],
home_ent:[
{t:'📈 趨勢',h:'迷你投影機從新奇變主流，電視掛架與 HDMI 2.1 線材穩定銷售',p:'$100-300 迷你投影機銷量年增 20%+，露營/臥室場景推動需求。4K 解析度逐漸成為入門標準。串流服務普及推動電視掛架、Soundbar 支架、HDMI 線材等長青品項穩定銷售。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['XGIMI MoGo 2 Pro Portable Projector','Mounting Dream TV Wall Mount','Amazon Basics High-Speed HDMI 2.1 Cable']},
{t:'📈 趨勢',h:'Soundbar 取代傳統家庭劇院系統，$100-200 價位帶成長最快',p:'消費者偏好簡單設定的 Soundbar 而非複雜的多聲道系統。Dolby Atmos 支援成為中高階 Soundbar 標配。$100-200 價位帶成長最快。Bluetooth 連接與 HDMI eARC 是基本要求。',src:'https://www.accio.com/business/amazon-best-selling-home-entertainment',products:['Vizio V-Series 2.1 Soundbar','Samsung HW-B450 Soundbar','Sonos Beam Gen 2 Smart Soundbar']},
{t:'📈 趨勢',h:'串流設備持續熱銷，Fire TV Stick 與 Roku 主導市場',p:'Fire TV Stick 穩居 Amazon Electronics Best Seller。Roku 在美國串流設備市場佔有率最高。4K HDR 支援成為基本要求。$25-50 價位帶銷量最高。Prime Day 折扣推動大量購買。',src:'https://whop.com/blog/amazon-trends/',products:['Amazon Fire TV Stick 4K Max','Roku Streaming Stick 4K','Google Chromecast with Google TV']},
{t:'📈 趨勢',h:'黑膠唱片機復興，復古音響設備受年輕世代歡迎',p:'黑膠唱片銷量連續 17 年成長，推動唱片機需求。$50-150 價位帶入門唱片機銷量最高。Crosley 與 Audio-Technica 品牌在 Amazon 上領先。黑膠唱片本身也是 Amazon 熱銷品項。',src:'https://explodingtopics.com/blog/trending-products',products:['Audio-Technica AT-LP60X Turntable','Crosley Cruiser Plus Portable Turntable','Victrola Vintage 3-Speed Bluetooth Turntable']},
{t:'📈 趨勢',h:'遊戲周邊配件市場龐大，遊戲耳機與控制器是最大子品類',p:'PS5、Xbox、Nintendo Switch 周邊配件市場龐大。遊戲耳機、額外控制器、充電座是熱銷品。$30-80 價位帶成長最快。RGB 燈效成為遊戲周邊標配。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['HyperX Cloud II Gaming Headset','PowerA Enhanced Wireless Controller','Razer DeathAdder V3 Gaming Mouse']},
{t:'📈 趨勢',h:'戶外電影體驗設備需求上升，充氣式投影螢幕與便攜式喇叭熱銷',p:'「後院電影之夜」成為美國家庭熱門活動。充氣式投影螢幕、便攜式藍牙喇叭、戶外延長線搜尋量在夏季翻倍。$50-150 價位帶的套組（螢幕+投影機+喇叭）銷量最高。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['VIVOHOME Inflatable Movie Projector Screen 20ft','JBL Flip 6 Portable Bluetooth Speaker','Anker Soundcore Motion+ Bluetooth Speaker']},
{t:'📈 趨勢',h:'智慧電視配件需求穩定，遙控器保護套與電視背光燈條是高利潤品',p:'智慧電視遙控器保護套、電視背光 LED 燈條、螢幕清潔套組是低單價高利潤品項。$5-15 價位帶衝動購買率高。「經常一起購買」推薦帶動銷量。電視背光燈條在社群上傳播力強。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Govee TV LED Backlight Strip','Fintie Remote Case for Fire TV Stick','WHOOSH! Screen Cleaner Kit']},
{t:'📈 趨勢',h:'Hi-Fi 音響設備從小眾走向主流，DAC 與耳機擴大機需求上升',p:'消費者對音質要求提升推動 Hi-Fi 設備需求。USB DAC、耳機擴大機、書架式喇叭搜尋量年增 20%。$50-200 價位帶入門 Hi-Fi 設備成長最快。Audiophile 社群推薦帶動 Amazon 銷量。',src:'https://helium10.com/blog/amazon-audio-trends',products:['FiiO K5 Pro ESS DAC/Amp','Edifier R1280T Powered Bookshelf Speakers','Schiit Modi 3E DAC']},
{t:'📈 趨勢',h:'家用 KTV 設備需求穩定，無線麥克風與卡拉 OK 機受家庭歡迎',p:'家庭聚會與派對推動家用 KTV 設備需求。無線藍牙麥克風、便攜式卡拉 OK 機搜尋量穩定。$20-50 價位帶最受歡迎。亞裔美國人社群是重要客群。節日季銷量翻倍。',src:'https://supplykick.com/blog/amazon-entertainment-trends',products:['BONAOK Wireless Bluetooth Karaoke Microphone','Singing Machine Karaoke System','JYX Karaoke Machine with 2 Wireless Mics']}
],

musical:[
{t:'📈 趨勢',h:'Podcast 熱潮推動居家錄音設備需求，入門級樂器套組受歡迎',p:'USB 麥克風、Audio Interface、監聽耳機在 Amazon 上持續成長。Podcast 創業門檻降低推動入門設備需求。尤克麗麗、電子琴、MIDI 控制器搭配教學的初學者套組特別受歡迎。',src:'https://whop.com/blog/amazon-trends/',products:['Blue Yeti USB Microphone','Focusrite Scarlett Solo Audio Interface','Donner Electric Keyboard Piano 61 Key']},
{t:'📈 趨勢',h:'吉他配件市場穩定，弦線與調音器是高回購品項',p:'吉他弦線、調音器、吉他背帶、Pick 是全年穩定需求品。弦線是最高回購率品項（每 1-3 個月更換）。Ernie Ball 與 D\'Addario 品牌穩居 Best Seller。$5-15 配件利潤率高。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Ernie Ball Regular Slinky Guitar Strings 3-Pack','Snark SN5X Clip-On Tuner','D\'Addario Guitar Picks Variety Pack']},
{t:'📈 趨勢',h:'電子鼓與靜音練習設備受公寓住戶歡迎，噪音問題推動需求',p:'公寓住戶無法使用傳統鼓組，推動電子鼓與靜音練習墊需求。$300-600 價位帶入門電子鼓銷量年增 20%。Alesis 與 Roland 品牌在 Amazon 上領先。練習墊（$20-40）是入門首選。',src:'https://explodingtopics.com/blog/trending-products',products:['Alesis Nitro Mesh Electronic Drum Kit','Roland TD-02K V-Drums Kit','Donner Drum Practice Pad 12 inch']},
{t:'📈 趨勢',h:'音樂製作軟體與 MIDI 控制器受 Bedroom Producer 推動',p:'居家音樂製作（Bedroom Production）文化推動 MIDI 鍵盤、MIDI Pad、監聽喇叭需求。Akai 與 Novation 品牌在 Amazon 上銷量領先。$50-150 價位帶入門設備成長最快。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Akai Professional MPK Mini MK3','Novation Launchpad X MIDI Controller','KRK Classic 5 Studio Monitor']},
{t:'📈 趨勢',h:'尤克麗麗持續受初學者歡迎，搭配教學的套組銷量最高',p:'尤克麗麗因為體積小、價格低、容易上手，持續受初學者歡迎。搭配調音器、琴袋、教學書的套組銷量遠高於單品。$30-60 價位帶最受歡迎。兒童尺寸也有穩定需求。',src:'https://www.accio.com/business/amazon-best-selling-musical',products:['Kala Learn to Play Ukulele Starter Kit','Donner Concert Ukulele Mahogany','Cordoba 15CM Concert Ukulele']},
{t:'📈 趨勢',h:'隔音與錄音空間改善產品需求上升，吸音棉與隔音簾熱銷',p:'居家錄音與 Podcast 推動錄音空間改善產品需求。吸音棉板、隔音簾、桌面隔音屏風搜尋量年增 25%。$20-50 價位帶的 DIY 隔音方案最受歡迎。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Fstop Labs Acoustic Foam Panels 12-Pack','NICETOWN Soundproof Thermal Curtains','Tonor Microphone Isolation Shield']},
{t:'📈 趨勢',h:'兒童樂器與音樂教育玩具需求穩定，木琴與迷你鋼琴是熱門禮品',p:'家長重視音樂教育，推動兒童樂器需求。木琴、迷你鋼琴、兒童鼓組是熱門禮品。$15-40 價位帶最受歡迎。聖誕節與生日是主要銷售時機。安全材質與鮮豔色彩是賣點。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Hape Pound & Tap Bench with Xylophone','Melissa & Doug Learn-to-Play Piano','Remo Kids Percussion Floor Tom Drum']},
{t:'📈 趨勢',h:'樂器收納與保護配件是穩定需求品，琴盒與支架利潤率高',p:'吉他架、鍵盤架、琴盒、麥克風架是全年穩定需求品。消費者購買樂器後通常會搭配購買收納配件。$15-40 價位帶最受歡迎。「經常一起購買」推薦帶動銷量。',src:'https://helium10.com/blog/amazon-musical-trends',products:['Hercules GS414B Guitar Stand','On-Stage KS7190 Keyboard Stand','Gator Cases Padded Guitar Gig Bag']},
{t:'📈 趨勢',h:'藍牙喇叭與耳機跨界音樂品類，Marshall 與 JBL 品牌效應強',p:'Marshall 復古風格藍牙喇叭在音樂愛好者中特別受歡迎。JBL 便攜式喇叭穩居 Best Seller。$50-150 價位帶成長最快。音質、電池續航、防水功能是三大選購考量。',src:'https://supplykick.com/blog/amazon-musical-trends',products:['Marshall Stanmore III Bluetooth Speaker','JBL Charge 5 Portable Bluetooth Speaker','Sony WH-1000XM5 Wireless Headphones']}
],
office:[
{t:'📈 趨勢',h:'人體工學辦公配件是最大亮點，模組化桌面整理器成為爆品',p:'人體工學椅墊、螢幕增高架、桌面線材整理器穩居 Best Seller。模組化桌面整理器登上 Amazon 全球 Top 10。遠端工作常態化持續推動 Home Office 需求。「辦公桌美學」成為社群熱門話題。',src:'https://www.alibaba.com/product-insights/top-amazon-best-selling-products-2026-market-trends-regional-breakdown-and-strategic-insights.html',products:['HUANUO Dual Monitor Stand','SimpleHouseware Mesh Desk Organizer','BenQ ScreenBar Monitor Light']},
{t:'📈 趨勢',h:'標籤機與收納用品需求穩定，居家辦公與小型企業推動成長',p:'標籤機、檔案夾、收納盒是全年穩定需求品。DYMO 與 Brother 品牌穩居 Best Seller。小型企業與居家辦公推動需求。$20-50 價位帶的標籤機銷量最高。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['DYMO LetraTag 200B Bluetooth Label Maker','Brother P-Touch Label Maker PTD220','Bankers Box SmoothMove Moving Boxes']},
{t:'📈 趨勢',h:'白板與會議用品需求穩定，磁吸式白板與白板筆是高回購品',p:'遠端會議與居家辦公推動白板需求。磁吸式白板、白板筆、白板擦是穩定需求品。可移除式白板貼紙受租屋族歡迎。$15-40 價位帶最受歡迎。白板筆是高回購品項。',src:'https://whop.com/blog/amazon-trends/',products:['Quartet Magnetic Whiteboard 3x2 ft','EXPO Low-Odor Dry Erase Markers 12-Pack','Think Board Peel & Stick Whiteboard']},
{t:'📈 趨勢',h:'印表機耗材是 Office 品類最大回購品項，相容墨水匣市場龐大',p:'印表機墨水匣與碳粉匣是 Office 品類回購率最高的品項。第三方相容墨水匣價格僅原廠 30-50%，銷量驚人。Subscribe & Save 在耗材品類滲透率高。HP 與 Canon 相容匣市場最大。',src:'https://www.accio.com/business/amazon-best-selling-office',products:['HP 67XL Black Ink Cartridge','Canon PG-245XL/CL-246XL Ink Combo Pack','Valuetoner Compatible Ink Cartridge Replacement']},
{t:'📈 趨勢',h:'筆記本與文具受手寫復興趨勢推動，Bullet Journal 文化帶動需求',p:'數位疲勞推動手寫復興。Bullet Journal（子彈筆記）文化帶動點格筆記本、彩色筆、貼紙需求。Leuchtturm1917 與 Moleskine 品牌在 Amazon 上銷量穩定。$10-20 價位帶最受歡迎。',src:'https://explodingtopics.com/blog/trending-products',products:['Leuchtturm1917 Dotted Notebook A5','Sakura Pigma Micron Fineliner Pens 6-Pack','Moleskine Classic Notebook Hard Cover']},
{t:'📈 趨勢',h:'碎紙機需求穩定，身份盜竊擔憂推動家用碎紙機銷量',p:'身份盜竊案件增加推動家用碎紙機需求。交叉切割（Cross-Cut）碎紙機成為基本要求。$30-80 價位帶最受歡迎。AmazonBasics 與 Fellowes 品牌在 Amazon 上領先。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['AmazonBasics 12-Sheet Cross-Cut Shredder','Fellowes Powershred 79Ci Shredder','Bonsaii 10-Sheet Cross-Cut Shredder']},
{t:'📈 趨勢',h:'辦公椅與坐墊是 Office 品類高單價成長品項',p:'遠端工作推動辦公椅需求常態化。$150-400 價位帶的人體工學辦公椅成長最快。記憶棉坐墊、腰靠墊是低單價搭配品項。「辦公椅開箱」在 YouTube 上是熱門內容。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['HON Ignition 2.0 Ergonomic Office Chair','Everlasting Comfort Memory Foam Seat Cushion','LoveHome Lumbar Support Pillow']},
{t:'📈 趨勢',h:'桌面螢幕燈與 LED 檯燈需求上升，護眼功能成為賣點',p:'長時間使用電腦推動護眼照明需求。BenQ ScreenBar 帶動桌面螢幕燈品類成長。可調色溫、亮度的 LED 檯燈搜尋量穩定。$20-60 價位帶最受歡迎。無閃爍認證是加分項。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['BenQ ScreenBar Halo Monitor Light','TaoTronics LED Desk Lamp','Baseus Monitor Light Bar']},
{t:'📈 趨勢',h:'Back-to-School 季節（Q3）是 Office 品類第二大銷售季',p:'Back-to-School（返校季，7-9月）是 Office 品類僅次於 Q4 的銷售高峰。筆記本、資料夾、計算機、背包搜尋量在 7 月開始上升。學生用品套組（Bundle）銷量高於單品。',src:'https://helium10.com/blog/amazon-office-trends',products:['Five Star Spiral Notebook 5-Pack','Texas Instruments TI-84 Plus CE Calculator','JanSport SuperBreak Plus Backpack']}
],
pc:[
{t:'📈 趨勢',h:'筆電周邊配件持續熱銷，AI PC 周邊市場正在形成',p:'鋁合金筆電支架、機械鍵盤、大尺寸滑鼠墊是熱門品項。隨著 AI PC 普及，高效能外接 GPU 底座、大容量 SSD 外接盒等新品類出現。USB4/Thunderbolt 5 配件需求預計 2027 年爆發。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Rain Design mStand Laptop Stand','Keychron K2 Wireless Mechanical Keyboard','Samsung T7 Shield Portable SSD 2TB']},
{t:'📈 趨勢',h:'機械鍵盤從電競走向辦公，客製化鍵帽與靜音軸體受歡迎',p:'機械鍵盤從電競玩家擴展到辦公用戶。靜音軸體（Silent Red/Brown）受辦公環境歡迎。客製化鍵帽（PBT 材質、主題設計）搜尋量年增 30%。$50-100 價位帶成長最快。',src:'https://whop.com/blog/amazon-trends/',products:['Keychron Q1 Pro Wireless Mechanical Keyboard','Akko 3068B Plus Mechanical Keyboard','HyperX Pudding Keycaps Full Set']},
{t:'📈 趨勢',h:'外接螢幕需求穩定，便攜式螢幕受遠端工作者與遊戲玩家歡迎',p:'15.6 吋便攜式螢幕搜尋量年增 25%。遠端工作者用作第二螢幕，遊戲玩家用於 Switch/PS5。USB-C 一線連接是基本要求。$100-200 價位帶成長最快。ASUS 與 Lepow 品牌在 Amazon 上領先。',src:'https://explodingtopics.com/blog/trending-products',products:['ASUS ZenScreen 15.6 inch Portable Monitor','Lepow 15.6 inch Portable Monitor','ViewSonic VX1655-4K Portable Monitor']},
{t:'📈 趨勢',h:'電競周邊配件市場龐大，RGB 燈效與高刷新率成為標配',p:'電競滑鼠、電競耳機、電競滑鼠墊是最大子品類。RGB 燈效成為電競周邊標配。144Hz+ 高刷新率螢幕需求穩定。Razer、Logitech G、SteelSeries 品牌主導市場。',src:'https://www.accio.com/business/amazon-best-selling-pc',products:['Logitech G502 X PLUS Gaming Mouse','SteelSeries Arctis Nova 7 Gaming Headset','Razer Goliathus Extended Gaming Mouse Pad']},
{t:'📈 趨勢',h:'NAS 與家用伺服器需求上升，資料備份意識提升推動成長',p:'雲端儲存費用上漲推動 NAS（網路附接儲存）需求。Synology 與 QNAP 品牌在 Amazon 上銷量穩定。搭配 NAS 專用硬碟（WD Red、Seagate IronWolf）銷量同步成長。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Synology DiskStation DS224+ NAS','WD Red Plus 4TB NAS Hard Drive','Seagate IronWolf 4TB NAS Hard Drive']},
{t:'📈 趨勢',h:'散熱與筆電冷卻配件需求穩定，夏季銷量翻倍',p:'筆電散熱墊、桌面風扇、散熱支架在夏季銷量翻倍。高效能筆電（遊戲/影片剪輯）用戶是主要客群。$15-40 價位帶最受歡迎。靜音設計是重要賣點。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Havit HV-F2056 Laptop Cooling Pad','TopMate C5 Laptop Cooler','Kootek Laptop Cooling Pad 12-17 inch']},
{t:'📈 趨勢',h:'Webcam 與視訊會議配件需求常態化，4K Webcam 成為新標準',p:'遠端會議常態化推動 Webcam 與視訊配件穩定需求。4K 解析度、自動對焦、背景模糊功能成為新標準。環形補光燈搭配 Webcam 的套組銷量高。$50-100 價位帶成長最快。',src:'https://supplykick.com/blog/amazon-pc-trends',products:['Logitech Brio 4K Ultra HD Webcam','Elgato Facecam Pro 4K Webcam','Razer Kiyo Pro Ultra Webcam']},
{t:'📈 趨勢',h:'DIY 電腦組裝文化持續，散熱膏與機殼風扇是高回購品',p:'DIY 電腦組裝在 YouTube 上持續是熱門內容。散熱膏、機殼風扇、RGB 燈條是高回購品項。$5-20 價位帶配件利潤率高。Noctua 散熱膏與 Arctic 風扇穩居 Best Seller。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Noctua NT-H1 Thermal Compound','Arctic P12 PWM PST Case Fan 5-Pack','Corsair iCUE SP120 RGB Elite Fan']},
{t:'📈 趨勢',h:'USB Dock 與擴充座需求穩定，筆電用戶追求桌面級連接體驗',p:'Thunderbolt/USB4 Dock 讓筆電用戶獲得桌面級連接體驗。雙螢幕輸出、100W 充電、多 USB 埠是消費者基本要求。$50-150 價位帶成長最快。CalDigit 與 Anker 品牌在 Amazon 上領先。',src:'https://helium10.com/blog/amazon-pc-trends',products:['CalDigit TS4 Thunderbolt 4 Dock','Anker 575 USB-C Docking Station 13-in-1','Plugable USB-C Triple Display Docking Station']}
],
wireless:[
{t:'📈 趨勢',h:'TWS 耳機平價替代品銷量驚人，Qi2 認證成為新賣點',p:'AirPods 替代品（$20-40）銷量驚人。MagSafe 相容無線充電板、車用無線充電支架持續熱銷。Apple Watch 錶帶、AirPods 保護殼等品牌配件平價替代品市場龐大。Qi2 無線充電標準正在成為新標準。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['Soundcore by Anker Space A40 Earbuds','Anker MagSafe Wireless Charging Pad','Spigen Rugged Armor AirPods Pro 2 Case']},
{t:'📈 趨勢',h:'降噪耳機需求穩定成長，ANC 功能從高階下放到 $50 以下價位',p:'主動降噪（ANC）功能從 $200+ 高階耳機下放到 $30-50 價位帶。通勤、辦公、旅行場景推動需求。Sony WF-1000XM5 與 AirPods Pro 2 穩居高階市場。平價 ANC 耳機成長更快。',src:'https://explodingtopics.com/blog/trending-products',products:['Sony WF-1000XM5 Wireless Earbuds','Apple AirPods Pro 2nd Generation','Soundcore by Anker Liberty 4 NC']},
{t:'📈 趨勢',h:'Apple Watch 錶帶市場龐大，第三方替代品銷量遠超原廠',p:'Apple Watch 第三方錶帶市場龐大。矽膠運動錶帶、不鏽鋼米蘭錶帶、尼龍編織錶帶是三大熱銷款式。$5-15 價位帶銷量最高。多色組合包（3-5 條）轉換率高於單條。',src:'https://whop.com/blog/amazon-trends/',products:['WFEAGL Apple Watch Band Silicone 4-Pack','Fullmosa Apple Watch Band Stainless Steel','Apple Watch Ultra Nylon Loop Band']},
{t:'📈 趨勢',h:'MagSafe 配件生態系持續擴張，磁吸式卡夾與支架是新爆品',p:'MagSafe 磁吸式卡夾、磁吸式支架、磁吸式行動電源搜尋量年增 35%。iPhone 用戶對 MagSafe 生態系的接受度持續提升。$10-30 價位帶配件利潤率高。Android 陣營也開始支援 Qi2 磁吸。',src:'https://salesduo.com/blog/amazon-trends-for-2026/',products:['MOFT Snap-On Phone Stand & Wallet','ESR HaloLock MagSafe Wallet Stand','Anker 622 MagGo Magnetic Battery']},
{t:'📈 趨勢',h:'藍牙喇叭市場成熟但需求穩定，防水與便攜性是關鍵賣點',p:'JBL、Bose、Sony 品牌主導藍牙喇叭市場。IPX7 防水、12 小時+ 電池續航、USB-C 充電是消費者基本要求。$30-80 價位帶銷量最高。戶外與旅行場景推動便攜式喇叭需求。',src:'https://www.accio.com/business/amazon-best-selling-wireless',products:['JBL Flip 6 Portable Bluetooth Speaker','Bose SoundLink Flex Bluetooth Speaker','Ultimate Ears WONDERBOOM 3']},
{t:'📈 趨勢',h:'無線充電多設備充電站需求上升，3-in-1 充電座受 Apple 用戶歡迎',p:'iPhone + Apple Watch + AirPods 三合一無線充電座搜尋量年增 30%。Belkin 與 Anker 品牌在 Amazon 上領先。$30-60 價位帶成長最快。桌面整潔與減少線材是主要購買動機。',src:'https://www.darkroomagency.com/observatory/which-amazon-product-categories-are-growing-in-2025',products:['Belkin BoostCharge Pro 3-in-1 Wireless Charger','Anker 3-in-1 Cube MagSafe Charger','ESR 3-in-1 MagSafe Charging Station']},
{t:'📈 趨勢',h:'骨傳導耳機從運動專用走向日常，開放式聆聽成為新趨勢',p:'骨傳導耳機讓用戶在聽音樂時仍能聽到環境音。跑步、騎車、辦公場景推動需求。Shokz（原 AfterShokz）品牌主導市場。$80-130 價位帶成長最快。開放式耳機（Open Ear）也在成長。',src:'https://www.bebolddigital.com/blog/top-amazon-categories-2026',products:['Shokz OpenRun Pro 2 Bone Conduction','Shokz OpenFit Air Open-Ear Earbuds','Bose Ultra Open Earbuds']},
{t:'📈 趨勢',h:'手機殼與保護貼是 Wireless 品類最大子品類，新機發布帶動換購潮',p:'每年 iPhone/Samsung 新機發布帶動手機殼與保護貼換購潮。MagSafe 相容、軍規防摔、透明設計是三大熱門款式。$8-20 價位帶銷量最高。Spigen、TORRAS、Caseology 品牌在 Amazon 上領先。',src:'https://junglescout.com/blog/amazon-product-trends/',products:['Spigen Ultra Hybrid MagSafe iPhone 16 Case','TORRAS Slim Fit iPhone 16 Pro Case','amFilm Glass Screen Protector iPhone 16']},
{t:'📈 趨勢',h:'智慧手錶配件市場穩定，充電線與保護殼是高回購品',p:'Apple Watch、Samsung Galaxy Watch、Garmin 手錶的充電線、保護殼、螢幕保護貼是穩定需求品。$5-15 價位帶衝動購買率高。新款手錶發布後配件銷量在 2-4 週內爆發。',src:'https://helium10.com/blog/amazon-wireless-trends',products:['Apple Watch Magnetic Charging Cable','Misxi Apple Watch Case with Screen Protector','Samsung Galaxy Watch Charging Dock']}
]
};