const NEWS=[
{tag:'AMAZON',date:'06/22/2026',title:'Half Your Customers Are Already Using AI to Find You. Are You Findable? - CMSWire',body:'Half Your Customers Are Already Using AI to Find You.',src:'https://news.google.com/rss/articles/CBMiqAFBVV95cUxPeGI1bXRjTmhtSElLd0hvTC00SHplSkpfS0d1UXp1VmdCVkJweU5fY19PdzhET2FOUVltUjhoU1U5VjBhYURPekdvd0pYYVlrSk1RYWZwLWdhUGQ2Y1AtS3FGamZlXzJSWlVfQjBIanA3RTQyQzNaSkJCeDBrMWJCZHpSOXBjU3dEMFFxQ2lubnBHbTM5WW9VaXJLZERoLV80QzdLNnBUNUU?oc=5',via:'CMSWire'},
{tag:'AMAZON',date:'06/22/2026',title:'Amazon\'s first ever ChatGPT ads reveal a key part of the e-commerce giant\'s AI strategy - Business Insider',body:'Amazon\'s first ever ChatGPT ads reveal a key part of the e-commerce giant\'s AI strategy  Business Insider',src:'https://news.google.com/rss/articles/CBMikAFBVV95cUxOcmlMQ0RwRDl4aml1S294TVRSQTAwZXdJbF9rUFhVWXd4LVdBcTMwTE1ILWJ4bXhwbW9KWVUwWXQtODRYMmpCdnNTUmxsSmx0Z19iYmFmamxXdkxQbkhCaFZrTHhlU20tRmZSSXpwdTV1N0NTNW16U2ktaVBMWDdINzNwcEJxcHBGUGR5OFZ1VUI?oc=5',via:'Business Insider'},
{tag:'TIKTOK SHOP',date:'06/22/2026',title:'Meet us at the Mall: JCPenney and Aéropostale Are Making Summer Shopping Rewarding - JCPenney Newsroom',body:'Meet us at the Mall: JCPenney and Aéropostale Are Making Summer Shopping Rewarding  JCPenney Newsroom',src:'https://news.google.com/rss/articles/CBMiwgFBVV95cUxORDhBdDZ2SklLNjQzd2VNZzRCVzJtTXA2bXlUR2UyQk1vZW1JcmVUOVlkRUM2S2dkenFERXQ3M0twNDJ3S09xSzlhbUpLYTAtNUxGMGtCWEUxeFdGM0lWS2hvNTZSR0lPVE5rRTZ1N0FQZjhGRmQ1YU5mM2o5REJZSFlBakZjRU9UWG9ZZmtKQTk0VTdLVFl1a1l1LXBvOG1QUzg1Q0pKLU0tU21rOHZJVldhU2trQ0o2ZUN1OVNfZ2N5dw?oc=5',via:'JCPenney Newsroom'},
{tag:'AMAZON',date:'06/22/2026',title:'Amazon A+ Content trains AI through conversions, not indexing - PPC Land',body:'Amazon A+ Content trains AI through conversions, not indexing  PPC Land',src:'https://news.google.com/rss/articles/CBMigwFBVV95cUxPcFJrQ3ZxQ3BWVHdJcTdSdXdYcWNWU1BRU3l5RTZYSzdSUGpRUUlFb1AtSmJQUk9WTTVqRkFBb2RqUnZUekpYWHJPbm9jbF8xWVhHXzVqS0syTk02MFA5bHYyUXkwQVNiQVhMcEFiOUNfNmU1RnFRQ0lIa21WLVpMRWp2dw?oc=5',via:'PPC Land'},
{tag:'AMAZON',date:'06/22/2026',title:'Conversational Visual Shopping - Trend Hunter',body:'Conversational Visual Shopping  Trend Hunter',src:'https://news.google.com/rss/articles/CBMiZkFVX3lxTE55NFc4eVhQMHpLbEpFanZsRWZPQjlOWjMzaXJHazhzNVh5ajRLME4tUS1INjg0UlBmTFJTWDIxdjV0cm4zMnFBQjVsZDhvNnUwRC1saTVoSkVDUFJieDNvRlpoOUMxZ9IBZkFVX3lxTE55NFc4eVhQMHpLbEpFanZsRWZPQjlOWjMzaXJHazhzNVh5ajRLME4tUS1INjg0UlBmTFJTWDIxdjV0cm4zMnFBQjVsZDhvNnUwRC1saTVoSkVDUFJieDNvRlpoOUMxZw?oc=5',via:'Trend Hunter'},
{tag:'TEMU',date:'06/22/2026',title:'Watch This Floridian Transform a BMW M5 Into a Supercar Thanks to Temu Parts - Yahoo Autos',body:'Watch This Floridian Transform a BMW M5 Into a Supercar Thanks to Temu Parts  Yahoo Autos',src:'https://news.google.com/rss/articles/CBMipAFBVV95cUxPTlRwcWhRRjJzOHRFUy1BRHB6eGNMSEZDUkNTdGlJVXdyeV9vc1Awc01iNWtsdkMtbzlhemR5c0RpQmwyTWJObkF2VGJScDF1MnpvMXFQSXdmb3VGUHJTYVpCb2xHQkxTNXVHc0xaWGVYLWVYWWhBWEFqS056dFBESUVlb21sVHAydFJ0cldXOHh5TTllYjJjQXNUVW8tT0tHTWE0Sw?oc=5',via:'Yahoo Autos'},
{tag:'AMAZON',date:'06/22/2026',title:'Prime Day Is Almost Here. It’s a Test of Amazon’s AI Strategy. - Barron\'s',body:'Prime Day Is Almost Here.',src:'https://news.google.com/rss/articles/CBMidkFVX3lxTE4xNFZoLWd5WjBwUjhNcXZ4UHZuYldSbEpobVVGb20zYUNtWHNZV01ZYWZ5QUN1bU5oblhWYW9MaW1RVDRWLW1yZXExSmpYWjFZS0V2VTRwN3c2QWVJS0JycE1feDRUSnhVWmp4YlRyREZkVlJSY0E?oc=5',via:'Barron\'s'},
{tag:'AMAZON',date:'06/22/2026',title:'Duluth Trading Co. Uses Amazon Fulfillment for Marketplace Orders | June 2026 - News and Statistics - IndexBox',body:'Duluth Trading Co.',src:'https://news.google.com/rss/articles/CBMioAFBVV95cUxOemp3bXE3dzZhUG5SdFJyd2U4ZjlwSzJQM3hoZExLUDFyMmNFUkxuZVljUE9rUllqT3p6dG40dF9vQzZlMV9XakYyMUhrWVNYb2Y0N0FpU0ViNWpodmR5QTJrWE5HRFNiWjZQQWVOcXZBY0FHTkxQYWdZMHVkakRpMi1CR2c5d0ZWREVFUk04OGNzZE9xQm5NaEdiQUx3eU5a?oc=5',via:'IndexBox'},
{tag:'AMAZON',date:'06/22/2026',title:'AWS Weekly Roundup: NY Summit recap, Local Zone in Hanoi, Grok 4.3 in Bedrock, price reductions, and more (June 22, 2026) - Amazon Web Services (AWS)',body:'AWS Weekly Roundup: NY Summit recap, Local Zone in Hanoi, Grok 4.3 in Bedrock, price reductions, and more (June 22, 2026)  Amazon Web Services (AWS)',src:'https://news.google.com/rss/articles/CBMi4AFBVV95cUxNU1ktSkVOR1d6bkIxbUpLS2tveThtLWNJQW5kcDVlRjcwRmgyRkViT2d5QktOU21jRjRTa28zVFdUQW1Fa0x6bnA3T2UtZlRtXzFSSE42R1FNbWg2NEsyVzNFb0U2YTU5WEM0RHNMOXJ2aFJzSTB0ZWNXdWxVY1RPRjVuVEppcUZDX1p5OTl5c2lxZlZfaFZTUnI0Wm5rUjQ4SmtXbV9wc21XMjVEMTQ1V2w4TlpPVTA4RWs3ZDRHNnluY0ZybWkzenNlcVhlQTJVXzhoR094Mm9hYmVHSTZBNQ?oc=5',via:'Amazon Web Services (AWS)'},
{tag:'SHOPIFY',date:'06/22/2026',title:'Whatnot-Shopify Integration Tackles Live Commerce Inventory Challenges - E-Commerce Times',body:'Whatnot-Shopify Integration Tackles Live Commerce Inventory Challenges  E-Commerce Times',src:'https://news.google.com/rss/articles/CBMiuwFBVV95cUxNNmg1Tk1mNlhSWkhQTHdhMXpHb094Q192N25Wbl9GczMzeDhYd3NqbDd1aDh4T0tBNlFob3ZLNDVDWm94RGRVNVRZTWFMMmxtNnV5Ml9EZkdjeGxJR2Nad181Y2JDTkVvWUNnQXZxemFSM0FYTGJMbWRDUEllSy1lNXdPdTFvZzIzNmQ5T3J0UmJsQ004NFNzTGhMa0JOVEdwdDJ2eFQtZDh3dU1UYjU3dUhIY2poT3RQMzg0?oc=5',via:'E-Commerce Times'},
{tag:'TEMU',date:'06/22/2026',title:'MF Doom estate and Temu reach settlement in lawsuit over alleged knock-off merch - Music Business Worldwide',body:'MF Doom estate and Temu reach settlement in lawsuit over alleged knock-off merch  Music Business Worldwide',src:'https://news.google.com/rss/articles/CBMivAFBVV95cUxPVWNvbkdPZHpkZ3QzN0ZocmdSakNKRkNGdi1UYWxSa2JhUGJtc0xlRWhoU1gyeE9IU2ZIZE9INEhQaE9aTUlyVXoydE1QR0ZPc3g4blJMNzRpRWg2WTd4Y2V4VGZxUHkybWcteS1aWlpXbFBMbGpzRF9pZUpwYnlWdGlJLU1aMHhjZUlpd0tneTVTXy1fUTBVdFdHeTJ3QkZrYXpBUUpOTU81aThEanhoQ3JlUS1FU00zNi03MA?oc=5',via:'Music Business Worldwide'},
{tag:'EBAY',date:'06/22/2026',title:'Ebay (EBAY) Q1 2026 Earnings Call Transcript - Fortune',body:'Ebay (EBAY) Q1 2026 Earnings Call Transcript  Fortune',src:'https://news.google.com/rss/articles/CBMiX0FVX3lxTE8wZUtyVDZ4YllUbUN6cG04THJ5bWk2ci1LT2VBYTlJZ0dheEtYd01fb1RPUEUtalphWmN1b3hicUxhR21IYVlNU2ZNN0FlSWdYSTU5VllNdXBtLURVYWxF?oc=5',via:'Fortune'},
{tag:'TIKTOK SHOP',date:'06/22/2026',title:'Vaseline is turning 2008 beauty hacks into TikTok Shop sellouts - glossy.co',body:'Vaseline is turning 2008 beauty hacks into TikTok Shop sellouts  glossy.co',src:'https://news.google.com/rss/articles/CBMimAFBVV95cUxQVzEyZXZmTmswN0ZvVGxfNEp6UG1PWE50c3AwYkRmODdFUzF4VkRha1dxUnI1NzE5TnU2MUJEempXaVZjNnVNMnpFdG5TMFdPb053QVJUVGcxbFRKRGszRElSd0ZGUTVqQ3FhM3hnMzRqRkZJQkdNWko4V1YxSkhhMktoVzRnUFJlVHE0M0FkR0FULXNBZ0x4MA?oc=5',via:'glossy.co'},
{tag:'GOOGLE',date:'06/22/2026',title:'From invisible to recommended: How brands become visible to AI shopping agents - Retail Dive',body:'From invisible to recommended: How brands become visible to AI shopping agents  Retail Dive',src:'https://news.google.com/rss/articles/CBMitgFBVV95cUxOd0NqRkZSTV9jOEZFOEZLRzhGa2tveGtfcW1Ya2JsV1pFLXhRdFg1WTkzWmxITllmUm5mNUVZSUpTOTlYVW9RT1pnNkdOTGRKcXptekYzYzh6Q1oyQ2pITlBrV1hYWnJlSmdHVlNTakNScmhFdm9FQXQ5cVNsbnd5RHpzbHZYYy1ORWJCUmFxNnRXNTRIYVZtanBaV216aGVLSjhGSlVIRU9nLVc4ZlU3YlRWZm5udw?oc=5',via:'Retail Dive'},
{tag:'WALMART',date:'06/22/2026',title:'EXCLUSIVE: Walmart Pulls Sam’s Club Deeper Into Its Ad Business - ADWEEK',body:'EXCLUSIVE: Walmart Pulls Sam’s Club Deeper Into Its Ad Business  ADWEEK',src:'https://news.google.com/rss/articles/CBMimgFBVV95cUxPRnN3aFJLZnJpYzYzWWJOazVCd3htTXRWUHQ2VjQwSDNFWWkwNmtpWHZQQ0VWZjJLbGtETW8zN0J1UVZDX0stbU9aNXVlQ0JvRFktcnctMnZLb0xBRXpmZ0F1MnBuODVCMU9yanVoSkVXTk9NeHVwVFlFTmpGN0drV1RtdV9BY3lEczRveGNGNjZpQjlnVm5pMFhn?oc=5',via:'ADWEEK'},
{tag:'TEMU',date:'06/21/2026',title:'PDD Stock Faces Wall Street Reset: Temu Expansion, Supply Chain Spending Pressure Outlook - Stocktwits',body:'PDD Stock Faces Wall Street Reset: Temu Expansion, Supply Chain Spending Pressure Outlook  Stocktwits',src:'https://news.google.com/rss/articles/CBMi5gFBVV95cUxNRi1DQVhzSDBDaHJiSnczS1RXWnFXa2E0RlZXZzZEbDdJRXZidEhXdExlT0R5VXN2WUVTbG1WVEphYm0zaDJhN1Y2cnUtMlNNNXIzaGxWbmZOVFA2cm9PNUtybXlfVEhVSFBvVDg2b0Z2MnJhOG5pUmIyVEVTMDM3NlA0VVpvbFdCTWtCdUdxWGR0ZnNIR1dWd2NqTzNVa3pVdjR0N1otU1J0WXNld2pxLTItV2VYR1FlT1lDMHBfbFZNSkxkbXh1Qk9BZ01RcWhxbDE5T3IydlMyMllJYnhDWTVmQUVJUQ?oc=5',via:'Stocktwits'},
{tag:'TEMU',date:'06/21/2026',title:'EU fines Temu marketplace 200 million euros - logos-pres.md',body:'EU fines Temu marketplace 200 million euros  logos-pres.md',src:'https://news.google.com/rss/articles/CBMif0FVX3lxTE0zN3JuNDlmLW11dG5fM3cyZGtUN3EzSHVWYlV3bHpOY0xXX0duc0ZHNUJDWGhBRHI3UGh4QjEtVDhUeWVGQV9MMXpYWmNrV3JJNVdsQ3EzcFFQalBMUWVHUXRrNlNWd1hucmdvVTgtQWFlaGJBRGM4VEd3Rm0zc2M?oc=5',via:'logos-pres.md'},
{tag:'SHEIN / TEMU',date:'06/21/2026',title:'Will it still be worth it to shop from Temu? - Times of Malta',body:'Will it still be worth it to shop from Temu?',src:'https://news.google.com/rss/articles/CBMib0FVX3lxTFAwWTlaX3AzNXJXOTFmQURuQmE5dVZMU19OUlBkTDg1M2FOM2lkd01fZ3dYLUVjbEVLQ2x0dUxBaXp3ZnBhSk9Wel9raTJXZnBPYU1kamhzYVZkTzcwTFpjN2FRWnhoZF9QZndzMFA2WQ?oc=5',via:'Times of Malta'},
{tag:'EBAY',date:'06/21/2026',title:'Why Did EBAY Stock Pop 6% In After-Hours Trading Today? - Stocktwits',body:'Why Did EBAY Stock Pop 6% In After-Hours Trading Today?',src:'https://news.google.com/rss/articles/CBMitgFBVV95cUxNdW51V3YwNUxyR01nZUEzdE11aW1aVDhGZEJTd2V0eE13OHBGTFNaQjJPWF9ZTF9pU1k5dEpVMnFjdFdYWl85d2dISTVfeWZWSGF6dVk4SW1iMEJxX0wwUWVLS0ZKSHNkMlFsZi13blNjX0J3NEhlWVZkS0xjaURZck16Uzd0a2NkV0l2SW00TURjb0tOQXFiTklvSTVYODdDeVA5TDJWcEVSeWpXNlI5WndIbE1TQQ?oc=5',via:'Stocktwits'},
{tag:'JD.COM',date:'06/20/2026',title:'JD.com Expands E-Commerce Operations into Europe with Rapid Delivery Services - asatunews.co.id',body:'JD.com Expands E-Commerce Operations into Europe with Rapid Delivery Services  asatunews.co.id',src:'https://news.google.com/rss/articles/CBMib0FVX3lxTE5CVmZ1VXh4Sk1RLVA4QTAzTEcyXzJMbVVKLW9WXy0zOGFWc3RWLVVoZXRuSGNjbnhkQ3lVams5enBHOEV0VlBZWEt0M01mY0w3bUQtWldrbHgxYXB2RS02d2ZOVUZFZkFaN3N2YkloUQ?oc=5',via:'asatunews.co.id'},
{tag:'SHOPIFY',date:'06/20/2026',title:'Best eCommerce platforms for auto parts in 2026: Shopify Plus vs BigCommerce vs X-Cart compared - AZ Big Media',body:'Best eCommerce platforms for auto parts in 2026: Shopify Plus vs BigCommerce vs X-Cart compared  AZ Big Media',src:'https://news.google.com/rss/articles/CBMi1wFBVV95cUxQZDB5RVFnckdiY1FPNTVYWDFaYXVXaFJQaXk2cWV6a1JJM1NpNmFNcjVUdFMzMFpOQzJXc3VUalI5X2wzeFREWDFPcS1Zcm9CNUNPN2VhTDNCV3YzTEd5VmcwNzR2c3RURERUZnhSTzZ0Mm9fM0ZwZ0xLMWZLOFdBb1NjXzNBZVZKUFg2aEpWTUFaZTRieXotd2N2S2JqeUItOXNOV0NsaE9adFBxRDg0WnN1Rl9SRlRDWDdjbUs1QUpocjhRWVRIMDdNbkh3czBCa0NlRGMwOA?oc=5',via:'AZ Big Media'},
{tag:'MARKETPLACE',date:'06/20/2026',title:'China’s e-commerce platforms help unlock global markets for South Korean brands - South China Morning Post',body:'China’s e-commerce platforms help unlock global markets for South Korean brands  South China Morning Post',src:'https://news.google.com/rss/articles/CBMizwFBVV95cUxOSFgyaURhb3I2ZjMzaTc1Q2dXeHZwRno1a3BqR1prdi1MaVE3NFpmOHBhY2xVN2JLbTBmTk40N0JIc3B5UUZmM05lRFNPVk9PZk14dDRDenNfcEdaQjhfNTA1cWNrMENpa3FNaDRDMElHSzhaNHN2MW50bF9kX2lpV2d6c0NCQ21XTWVjRFVmeEVVTU1qUk8zc0VQVjZ2MEpwYWxVT3E4dy1zSzRXWjVxZ29VSzhhSWlxaTRlWmpXSnJsYjF0aThwVzJRemtMNlnSAc8BQVVfeXFMTlJkanRtX1J2Y01mbVpoRWtjUGhndGJrNkNRekJ2WDMzRldUYXFkRUdaczIwZTctZERVa2x2WlQ3NTI2aTFYamxmMEdVVjRqNG9NNURxa1lONEFWWlkyWXE3Yy1tczdlRHRUekRhYWprb1ZlZ1YwODhLTXRyTGR4SXZTcEg4YUhSYnFYM1RUUERiYlA1a093STN4cUdGQmt0djB6di1sMjIybno4YTJfLVlxellZQUhKMDloTW1DMC1YNDRJeWVDU3B5MWdJTW5j?oc=5',via:'South China Morning Post'},
{tag:'SHEIN / TEMU',date:'06/20/2026',title:'Temu’s bargain empire meets its biggest test: Can ultra-cheap shopping survive a post–de minimis world? - MSN',body:'Temu’s bargain empire meets its biggest test: Can ultra-cheap shopping survive a post–de minimis world?',src:'https://news.google.com/rss/articles/CBMi-wJBVV95cUxQMFhXdG91UlU2MGROb1pNbFQwM0JoTkdBV1ROUENHNmt5Z0d6d3dsRlE5OVFaWFpuMy1kell4blpEbnpyVl9oeEtNYmZnYy1oSHpOVDdKNENKS2x5VHVfRm16dTdVS2VRXzRqaTkwSFFObVZ3UlJHdGV4M2d2REtHeTh6R0VjTllLMnRLLXFBQ2twbFJUY09KUGd4MDJkTDRTb3ZFbklUV3ByTnlkOXpISTF1QkFqVmZpaGx4M2VlYmplM2pwS3R0bWpiOGRIZ2V3S3h6MFdjMkhHdl9EY1JSNkRTb2RXUlR0ZDY1QUhVZUZ1V3lYQWRuek15VlVwZlRBb2JWUnl6ajNaN3hXTkpSV1pyX2VPNnFSZGlkZjhMckhBeklYZEV3VE9vMHZkckVLcmdNbDlHWFZvNmRVLUktYkdIUHFKUV9zb0p2ZVVGN1hoYk1WdDkteTJJNVh1WHMyTVE4ZDlsakVVZFFoNUVXakV0QVFuenJUTXVN?oc=5',via:'MSN'},
{tag:'AMAZON',date:'06/19/2026',title:'Webotee Brings Amazon Market and Seller Intelligence Into Claude and ChatGPT With a New MCP Connector - The National Law Review',body:'Webotee Brings Amazon Market and Seller Intelligence Into Claude and ChatGPT With a New MCP Connector  The National Law Review',src:'https://news.google.com/rss/articles/CBMitgFBVV95cUxOd2NOUmlVMFlSSmg2VkNiVkNPNDJRcXJTUTE1VnhWMjV5ZDdLcFFmV2xHbV9ySkU2T2pzQmJJQUFXcEswOFhhbUdUd2xBM2I4YWlqODN6bEFJQ3pWeXY2d19GNjFXa3B5TTNNS2lrMjB5dGhETmREUWtyeTNFUkxTYjNoRzF0LTFteUhjYnRINFowOTc4ODlZZ2YwODJyRF9ZbkJwN3lPYUlhRDVRa09iLTJWb0tRQQ?oc=5',via:'The National Law Review'},
{tag:'EBAY',date:'06/19/2026',title:'Q1 Earnings Outperformers: eBay (NASDAQ:EBAY) And The Rest Of The Online Marketplace Stocks - Yahoo Finance',body:'Q1 Earnings Outperformers: eBay (NASDAQ:EBAY) And The Rest Of The Online Marketplace Stocks  Yahoo Finance',src:'https://news.google.com/rss/articles/CBMipAFBVV95cUxOUjNtVDlreFdkV3QtRE8xeGpURUxydUpHbkZMb1N6TTRkbU9melVnbVIzUUFCQS0xYlpFQnI5NjBaMVROamlsNGxNOEtmeFBGQXJjV0xJWjF2Y2Noc3FpdWVtcTVDM05URE9DdlhtamVpRVJUZWNycm1uOG9YeTJEWjhzWnY1TU5wcnY2NndVNXc0SHRGTGcyRkhuOC1ITUtteVFfWQ?oc=5',via:'Yahoo Finance'}
];
const DAILY_SUMMARY={
  date:'2026/06/23',
  points:[
  ]
};
