const NEWS=[
{tag:'SHEIN',date:'06/08/2026',title:'Is Amazon Haul worth it? How it compares to Temu and Shein - Techlicious',body:'Is Amazon Haul worth it?',src:'https://news.google.com/rss/articles/CBMiakFVX3lxTE1GRkppei1CVW14UU5WLXE3WHlwVGFpX1AxQjBJQzFkWjNCYVFXM0lPamVza2xqcjZGR1Z2VXRJNzR1WDJ0cVBQY0R2RW1rN2VIdTRJd0p5X1VoUVphOGppQmFSNWtqS3NSaHc?oc=5',via:'Techlicious'},
{tag:'TIKTOK SHOP',date:'06/08/2026',title:'TikTok Shop Bans AI Voices From Livestreams - PYMNTS.com',body:'TikTok Shop Bans AI Voices From Livestreams  PYMNTS.com',src:'https://news.google.com/rss/articles/CBMikAFBVV95cUxQZ2c2ZmI1cVNNcUFHVnpIazc5UzBfMGlyUnp4blEyTGNkT3Z5akh5ZXB6MzM3eXoyb25LeFJNVEJKLUY2TE5VY0I3VjdxalE2dFlodWl3M2FpVU1DOUl1SmZNVmQteWNGV3had09CbU1vcFQxSG5zUHRxR2pEc2tubVpYS3hObVdfUGhIOHFWZ1I?oc=5',via:'PYMNTS'},
{tag:'SHEIN',date:'06/08/2026',title:'Shein, Temu Face Double Squeeze From De Minimis End and Surging Jet Fuel - wwd.com',body:'Shein, Temu Face Double Squeeze From De Minimis End and Surging Jet Fuel  wwd.com',src:'https://news.google.com/rss/articles/CBMizgFBVV95cUxNUVU3dHd3V291TGYwVnlQZkV4WFpiNkRhdGx4N2Z4aG5jZDAtdlJ6UnhGWjFBYlpyYndnM2JzczRRajU5S083REtHdVhtZkxlUy1kcm92dkRGdHhrYU9hTVBXSW56LWEzOExBWFRkLURId1FlNTFTTUlTWnpsaFY0cnVUSTh1SkVlYWJ3X3VMLVQ1VXFtbXNKT0lBcmVUQ3FZRzhZdTR4VXhSUWlRa2dnWE1QVzNjOGRSZnVuU2NURndsbEg4Ym9IMTIzU29qUQ?oc=5',via:'wwd.com'},
{tag:'BNPL',date:'06/08/2026',title:'The Innovators 2026: Africa - Global Finance Magazine',body:'The Innovators 2026: Africa  Global Finance Magazine',src:'https://news.google.com/rss/articles/CBMidkFVX3lxTFBHOFJHQ21MWlBta204TlFHZXUtd2NubEs3SFV4OEpDZmNCMjFTbDN6RDBHTDhJZE53TW1fdGhEbVk0cHlUNFBLYnYwS0lpUzA4VE9BT1dRdXUwVlR1M216M2hHS1FXa0hXeTA1WDFUZkFwTF9wT2c?oc=5',via:'Global Finance Magazine'},
{tag:'TIKTOK SHOP',date:'06/08/2026',title:'Bellavita Luxury Secures Back-to-Back Selection for TikTok Shop\'s Super Brand Day, Bringing Its Most Ambitious Campaign Yet - markets.businessinsider.com',body:'Bellavita Luxury Secures Back-to-Back Selection for TikTok Shop\'s Super Brand Day, Bringing Its Most Ambitious Campaign Yet  markets.businessinsider.com',src:'https://news.google.com/rss/articles/CBMijgJBVV95cUxOSVVYX0YyTjBmeWdTYmE5Rl9xN3JsYlhsVWZrb3ZzRUdDWTNITEVJXzlwMzdOT29oZ0pSblYyM0s4RVhNMnY3cEpBYW40OXBHczZ6dGxCUkRDdUI0NkZqUW5vVzBQekNsc2ZLbmRrN3ZWb2dPUDRBSjcwUk5oQ2dDeEdfMHJmYUd4TWxjeWZJVVBHM0JSOXlEWG9SQ2gzWDJRajNiNGJEdjdSa1VpOXVmdElsMUxna3YyU0t2aWdudndadG1fZ0NqVGtWQmRMbmV5ZGREWnNGZWJDUzdtRGJ0dzktZmxheVJqWGdpUF9Qd2ZoOXJpYllZLXBwc2ZRaWlkbWl4WXBRWGdJOXJjRkE?oc=5',via:'markets.businessinsider.com'},
{tag:'AMAZON',date:'06/08/2026',title:'Last-Mile Delivery’s Safety Problem: The FMCSA Gap in the Amazon and FedEx Era - JD Supra',body:'Last-Mile Delivery’s Safety Problem: The FMCSA Gap in the Amazon and FedEx Era  JD Supra',src:'https://news.google.com/rss/articles/CBMiigFBVV95cUxPeFN6MjgxTTVqRERtQVBxanZONUpkZlZTSnlUb3hmQld2YzBQaEtKVWtXQ0lNaWU3SS1DbGZMcE9mRFFXUDU1MVFkNzh3dWJCb1FEaVh3ODFEd0phcko3WUkzOEtDM1ZqSFhjc0NzNDh3Q0loc0lRXzdYUUxnWlQ2aWNMMzUwZUdYSmc?oc=5',via:'JD Supra'},
{tag:'AMAZON',date:'06/08/2026',title:'What happens after your Amazon honeymoon ends? - Drug Store News',body:'What happens after your Amazon honeymoon ends?',src:'https://news.google.com/rss/articles/CBMie0FVX3lxTE1Gc1hzUk50Zkpva1JCUEkzdlhkc21QZlk4aGJ5RUhudkZrYTNjUkpKVW5yeThzUXZ2d3drUndKenkzbXYxMUtJQ2ZtUGhGbG1UWlV0VXU4VW9ZTnEwLWd5TWRPRk1hUlByMWJ5YlhwcDR1VmNDZEt2UWdfMA?oc=5',via:'Drug Store News'},
{tag:'TIKTOK SHOP',date:'06/08/2026',title:'Unveiling Germany\'s Social Commerce Boom: From TikTok Shop to Retail Media - GlobeNewswire',body:'Unveiling Germany\'s Social Commerce Boom: From TikTok Shop to Retail Media  GlobeNewswire',src:'https://news.google.com/rss/articles/CBMi4wFBVV95cUxQWHlPUkVIMlRxdGxtVTE3UHhpMkNjRGg2OW00VXZlWlVUTU9kNnFiTGR0cWNtUEs3TFRsZzBzdF81S2o2dEY2d3F1bVExR3NVb2JqUTlqYVdyLTY5QXZ1Z1lTZkVfSk9maUxyNzNQRkUtNEdtaEZhUU01N3pXOHQ3TzRnX2Y2RF9LcU5kZWdOcnR4dHJNREs5M3F2RmFoMjRBY2xpWXk3NEhENHFrQmk4UU1qczZ3T0g5TzBEOTV3M2lHN280SG5qVGRNUG92NHBZT1VrbjB0MnROTGlRTjFGT1FkOA?oc=5',via:'GlobeNewswire'},
{tag:'EBAY',date:'06/08/2026',title:'Ebay (EBAY) Q1 2026 Earnings Call Transcript - Fortune',body:'Ebay (EBAY) Q1 2026 Earnings Call Transcript  Fortune',src:'https://news.google.com/rss/articles/CBMiX0FVX3lxTE8wZUtyVDZ4YllUbUN6cG04THJ5bWk2ci1LT2VBYTlJZ0dheEtYd01fb1RPUEUtalphWmN1b3hicUxhR21IYVlNU2ZNN0FlSWdYSTU5VllNdXBtLURVYWxF?oc=5',via:'Fortune'},
{tag:'AMAZON',date:'06/08/2026',title:'Amazon.com, Inc. (AMZN) Stock Price, News, Quote & History - Yahoo Finance',body:'Amazon.com, Inc.',src:'https://news.google.com/rss/articles/CBMiTkFVX3lxTE5wLXdlSm5MT0hsWEI2RjNWUHB6R3FYWEYzbi0ydDM4NGFScjNIZmYwYlpGQzRVWmdrVHJHcnRJdFdrMkxFczJqYnE2VFNWQQ?oc=5',via:'Yahoo Finance'},
{tag:'SHEIN / TEMU',date:'06/08/2026',title:'Chinese online giants Shein and Temu have found a way to bypass the duty that the EU is introducing from July 1 - Inbox.eu',body:'Chinese online giants Shein and Temu have found a way to bypass the duty that the EU is introducing from July 1  Inbox.eu',src:'https://news.google.com/rss/articles/CBMi6AFBVV95cUxPal9rZ3dWTVVOM1hldHU1d3N1MkZTYzFIbUQtV1ExeEt5YjcxWm1kVFBwQWEzU2FoWUo3THUxY0Q4X2pySHl2Zk9FR1l0bmFpdEdzMXJSYlliMTd5S1dRa2hINS1IUml4dThiWnVVYlMtSTNiYW1XMm1zeEtNbkhiOE1kc1pmcmNreFl4M2REMmlhZXpKQ1laUHp4YVVaMTNFQlVzN1NLbHdpUWMwMFNWX1lvaUlCZ0l4LXZzNERVSHJIUnVueWJJbGpOODhQS1RES1R4ZUlQUnJQVER1c1lvOTJDdm1UbGlw?oc=5',via:'Inbox.eu'},
{tag:'TIKTOK SHOP',date:'06/08/2026',title:'TikTok Shop\'s tightening grip: new rules that could freeze your account - PPC Land',body:'TikTok Shop\'s tightening grip: new rules that could freeze your account  PPC Land',src:'https://news.google.com/rss/articles/CBMikAFBVV95cUxNZ1RmeGZhWWpqNkJET1BVUlphOHZjUE44d1VuUXRFVkRfVnJCWWlyX05iUzFVbnAtbWtPS2FQaHNmZDVFVGkzX0tCNm5TRmlFOTZLbk9nUGtlaXM1ZkpadXVRMXhzVld4YzFiNHhsRTh0WkZuMWhfLTBGZXFQdHVNZUxhbWVrV2RMVHVxTnBJelY?oc=5',via:'PPC Land'},
{tag:'MARKETPLACE',date:'06/08/2026',title:'Emma Hintz curates online marketplace for sustainable, women-owned fashion stores - Daily Bruin',body:'Emma Hintz curates online marketplace for sustainable, women-owned fashion stores  Daily Bruin',src:'https://news.google.com/rss/articles/CBMitgFBVV95cUxNeGlTbEllU3QwS3c1Mi1MX2ZNY2ZKYXpTV0FnWkY2RjI2dnJ6RURXUnlEMlJlMlpNaE5zRHRhcFdwNGNxMmpfZ252S2o4UEpjYkJlRnZ3azBxem5lRVhOdWljS0VKbk1BRC0yT1FNSkliRWw3RFlCMEhHUTFxeWZ6TE8wU2VvenY5NjFzSXJwVndzOGhtVFBhbmlVenFiNmw2NWhCVW1YVG9OWjFBaHhPeHdnX2JuQQ?oc=5',via:'Daily Bruin'},
{tag:'AMAZON',date:'06/08/2026',title:'Walmart goes global with its Amazon-like flywheel - Modern Retail',body:'Walmart goes global with its Amazon-like flywheel  Modern Retail',src:'https://news.google.com/rss/articles/CBMikwFBVV95cUxQNS1GNkhsdWFDdzZsLVNySUh5VnRVNXYzUDktOGs3NklqQUlTWDRlYnVOYU9RTVpTYnI1QXVFNThmUy1nMVNObmpob2Ffck1heWpfa3R0T0pBNHdkcF9fcktZRUZaN3ZiSTdubnlTay1jd2haTWs2RmU4S2t6MVNyUHVOZkJ5SWR5Ml9jQUhJMTZUbTQ?oc=5',via:'Modern Retail'},
{tag:'AMAZON',date:'06/08/2026',title:'TikTok now has a seat next to Amazon and Walmart in RFPs - Digiday',body:'TikTok now has a seat next to Amazon and Walmart in RFPs  Digiday',src:'https://news.google.com/rss/articles/CBMikAFBVV95cUxNNG8yTUdBVW5oVWR2ZXRwZDRJck0wUEllYkdxbzRpNWpHWjdQQW9DaGNKN052ajQtVnJyM1J1ekxJckhCdkdzNV9GZnJEX2VmSjM1UUx1MjZBRXVVMzNJdzNRbjRqQzlDQUVDc1ZlWW90STRmQ3BfVWNaR2tLNDZOUFBZVTZBcDNvbXJxVGhlb0w?oc=5',via:'Digiday'},
{tag:'SHEIN / TEMU',date:'06/08/2026',title:'China\'s E-commerce Exports Grapple with High Jet Fuel Costs Amid Global Conflict - Devdiscourse',body:'China\'s E-commerce Exports Grapple with High Jet Fuel Costs Amid Global Conflict  Devdiscourse',src:'https://news.google.com/rss/articles/CBMi0wFBVV95cUxOZ2VLVEVYSFNSN0t1ak10WUFacjRTZjBtdEJTTm9iWnpYbzgwNTUzOWYzekc0UkVqMEpXZkhzU2xkekNhaVpWQkpfOTFFeUZwUjg2b0p4YlY0NEV1YXctR1hINkg0OGlCZGY5dlNSODNsVm5maXE3dG5QeURkckhjWVRyMnNFUi1ZWS10ekxzNGdnZmdqWHUyM0tyRXQ3Q0VFc0RpSDVXV2FodmZOY1lzRGJsZ19kQ0Q1U1ZQSUN2N09wcU5FaDRSaWRObWh1QXRtTS040gHTAUFVX3lxTE5nZUtURVhIU1I3S3VqTXRZQVpyNFNmMG10QlNOb2JaelhvODA1NTM5ZjN6RzRSRWowSldmSHNTbGR6Q2FpWlZCSl85MUV5RnBSODZvSnhiVjQ0RXVhdy1HWEg2SDQ4aUJkZjl2U1I4M2xWbmZpcTd0blB5RGRySGNZVHIyc0VSLVlZLXR6THM0Z2dmZ2pYdTIzS3JFdDdDRUVzRGlINVdXYWh2Zk5jWXNEYmxnX2RDRDVTVlBJQ3Y3T3BxTkVoNFJpZE5taHVBdG1NLTg?oc=5',via:'Devdiscourse'},
{tag:'EBAY',date:'06/07/2026',title:'UBS Raises eBay Price Target to $110: Is the Online Marketplace Veteran a Quiet Winner? - AOL.com',body:'UBS Raises eBay Price Target to $110: Is the Online Marketplace Veteran a Quiet Winner?',src:'https://news.google.com/rss/articles/CBMifEFVX3lxTE1sRmItVHdlM3c0dGxhWWJSUkRIZEplMF94S0xFUnJORTFWUVhQWkZCZHBYaDE3S2FGQndfaWJLUVNMc3BYVkhfc0FGWGRwcmY0QTg0V3BYcndhb1lpSGZwb0JJTDFnN3haa0RabnBYejltcnJBZW84SUNWaUQ?oc=5',via:'AOL.com'},
{tag:'AMAZON',date:'06/07/2026',title:'Amazon mystery boxes tempt the curious - Northwest Arkansas Democrat-Gazette',body:'Amazon mystery boxes tempt the curious  Northwest Arkansas Democrat-Gazette',src:'https://news.google.com/rss/articles/CBMiigFBVV95cUxNdzNYUnBBT0pDXzFzRUJuaXA1LXQycWhJOGFJa21oT1VFNk5FR0xmaGpkemU0c0RFTVQ2R2lhWmpDejNNOXdDZmxYMHdza1gzaVlYWklybGJHVWxLNzhhVndad3ZYbTdoX29KeHNfNm5ZV1pQb0lSaTk5eVc1dG5uYng1UU5BcW5ieHc?oc=5',via:'Northwest Arkansas Democrat-Gazette'},
{tag:'SHOPIFY',date:'06/07/2026',title:'Generative AI Use Cases in Ecommerce - Shopify',body:'Generative AI Use Cases in Ecommerce  Shopify',src:'https://news.google.com/rss/articles/CBMidEFVX3lxTE91bzZ2Y0NRZnZCT3U1V1F3WFdpUURZN3hVa2R1VFZYNXp5ZVV4Q01ma3h1U29uMERUdXNvTkN2RDdUNTJHN29OUnhHY1FYYmtJM2dMdHJQQjFpOElNRUp4SkU5R094WDBKSmhaWmpreThQaThs?oc=5',via:'Shopify'},
{tag:'GOOGLE',date:'06/07/2026',title:'You Should Remember This Warning When Using An AI Shopping Agent - AOL.com',body:'You Should Remember This Warning When Using An AI Shopping Agent  AOL.com',src:'https://news.google.com/rss/articles/CBMihAFBVV95cUxQdklaX2JPVllxamZoeGtlaXZhd2VmQmowLTlEX09nVWwwRWNxLXF5ZzJXeS1ObnFURzNMRUYtYU5qc21tMVNST0ctcEE2d1FlVm04VTlMblZsdlRaT2wtSDc3T19JREs3NFd2a3FhTmFOeUk4d0NBdFVRd1FCc2hSR2czMmc?oc=5',via:'AOL.com'},
{tag:'SHOPIFY',date:'06/06/2026',title:'Shopify Online Store for US Businesses and Creators - AD HOC NEWS',body:'Shopify Online Store for US Businesses and Creators  AD HOC NEWS',src:'https://news.google.com/rss/articles/CBMirwFBVV95cUxOWlBybUZ6VjBXNnB3RG83al9EQkpNRURJeDVxQzZKY2V1RG1jQ0VWLUxsNnhkYWp6YmE2SGdIaTVHb0tJZHFkS25JekQwSTlDRk5tQmJtWUZYTi1QbmJJWlBab1VtQjJJR1RTUTRNTEF0WnI5ZVd0Vl9hcFRMalUtdEZRT2hrZG5ZaFdIRW5CNmNmOGlVU0VnVGJlRXh3WExEY3lNTDFxbXNsOXd5aEVV?oc=5',via:'AD HOC NEWS'},
{tag:'SHOPIFY',date:'06/06/2026',title:'Digital Business Transformation in Ecommerce: Keys to Success (2026) - Shopify',body:'Digital Business Transformation in Ecommerce: Keys to Success (2026)  Shopify',src:'https://news.google.com/rss/articles/CBMidkFVX3lxTE1lS19lXzA5ay1qWTh6cUY0MW83ck9seGdYMHZMMGhpYWhyaU90NmZGTThGQ0hzTjhKNks2MXNHRmRMZjBKSVJYRUpPOUR1ejkxMFJZMl9mTWZsb1c2SGFockFqRU1FUFo1SlhOT25GQnQtaXF4RGc?oc=5',via:'Shopify'},
{tag:'SHOPIFY',date:'06/06/2026',title:'What Is an Omnichannel POS? Features and Setup Guide (2026) - Shopify',body:'What Is an Omnichannel POS?',src:'https://news.google.com/rss/articles/CBMiZkFVX3lxTFBaSmY5Uy1pSVpDUXFoY2ZQemgzUEJVdVkzcTZyZWVHYjNrRm9HRDB2cnp3TFVVU05kdGhXTmJ0c3N5aGNjRnRPM0x0OXgtRGgxNWNJWEloRU9MS3lyYTJxMDY3UUE5UQ?oc=5',via:'Shopify'},
{tag:'BNPL',date:'06/05/2026',title:'Klarna Says \'Buy Now, Pay Later\' Users Agreed To Arbitration - Law360',body:'Klarna Says \'Buy Now, Pay Later\' Users Agreed To Arbitration  Law360',src:'https://news.google.com/rss/articles/CBMingFBVV95cUxQUkk4X2tQRThJWWFic3I1TE5DWXZUTmhhLVpINUFhQUZtT244bE04d3JfRC1HUlBtLVgzSlJXajZSeFp2cGRscGxGTURkckJnY0wzR0R4ZlVQWmxhRlJDNm9naHh3alhSU0VpUk5zNEQ5dF9PVHM0eDFXTDMtLUFUSXBFMDMxU0Rxb3loZmphQlU5N25BZlQxZnJKTlQ1d9IBVkFVX3lxTFBnbldJeDJ4V2I4UWVVU3VBSGxtOGJCaUM1Z3VIT2ZaOVVUUzFybzlLYUEyVm92dmh1X2t3Z2ZXeExGYTlIT2FLX1ZwekV5aFFyX3h3UERR?oc=5',via:'Law360'},
{tag:'SCOTUS',date:'06/05/2026',title:'Update for HFA Members: IEEPA Refunds and Supreme Court Appeal - Home Furnishings Association',body:'Update for HFA Members: IEEPA Refunds and Supreme Court Appeal  Home Furnishings Association',src:'https://news.google.com/rss/articles/CBMijgFBVV95cUxQOEdvMXRTaGdTSllxTFUzdUFIVHZaVGE2VExDYmFaZHQ1NmN0NDFIRVVyYUZLRHp1OUZYM013Yko5RXVOTDVYbTdxalFPOFpVTEtjSEhJZlFzMGZuNnloZHRaenB2dW95R25ZUmpkbE5kZjI5ZjZxYk5zOTVDTEFRVC1qNTRzR3ZwYmRFbi1n?oc=5',via:'Home Furnishings Association'}
];
const DAILY_SUMMARY={
  date:'2026/06/09',
  points:[
  ]
};
