const NEWS=[
{tag:'TEMU',date:'09/15/2026',title:'Illegal BTS ‘Swim’ copies sold on Temu - The Korea Herald',body:'Illegal BTS ‘Swim’ copies sold on Temu  The Korea Herald',src:'https://news.google.com/rss/articles/CBMiV0FVX3lxTFB1dW9CNUNJd08wbnJhcm54SkJ5Q1M4MWJCM09pU0F6alNFckJrNnBTVFNPczdjRHEta2xWeVE5bC1JOG1QdHpXbmljZWVMazVQTHNWTU9SNA?oc=5',via:'The Korea Herald'},
{tag:'AMAZON',date:'09/14/2026',title:'Amazon Great Indian Festival 2026: Rufus AI reveals possible sale dates, deals and ways to save more - Business Today',body:'Amazon Great Indian Festival 2026: Rufus AI reveals possible sale dates, deals and ways to save more  Business Today',src:'https://news.google.com/rss/articles/CBMi-wFBVV95cUxOcVd0VGZnazE5aFVOWDVtYWk1MWRZSllRRE80d082Q2pQeTAtNndMZ0EtQ1VKNXl3ZWFHMlB3U3V5VGVUdmlrLUVoNmZhN2ZOM3RPa2RZMVBJZC0zd3JGSXdiUEMwMk5Ia04zRW5kdVZPQkhyZXkyM3pQTXpZUE5MNHRSdlBmOHo3QmtWY1g4OUdGMk1Xelc1NVZ0d3ZSVmtCbEFBeE5mMS1WMm9PanBPNTdmUTUyUnlIZUdMZVZpM2h5Zk41NWNhMGNxRnM2Z2J5cDgzalYxOTJveTNEekhuVWZpTVJueGd6X1pILUNXUmQ5b0dNSWxjR2NEZ9IBgAJBVV95cUxQUTEzZEJkd1hlNXZVQURKTHRITFBsSkhGUGlVRWY4elJRaWhhRGtpOVFJYkppTVh2ZW5NYndQUDk2Rjh3dmIzSm9NbkRsUVU2ek1tRUxKSU14LUFlR2Fvbl9MYm44SG5KRk1RYi0xNnZBWnpDU21BOFdTcUtvOE1kZi1Bb3RSWVBtMUEzd0FMVHlRSFYxUzRyUWl2MjVnNnluUVBxOTlOOENjZUxEcW5sSlF6TU1BTFdzcnRsclNiRUh2dUZLNWNSQnRXRW5icWdRdlVkMHFFd2tCUTAzV3psLThEaEhfamNwc2NzUUYxQzlOdi16dlFZdmVicnZ2QjNl?oc=5',via:'Business Today'},
{tag:'SHOPIFY',date:'09/14/2026',title:'Shopify Says AI Search Boosts Conversions by 80% - PYMNTS.com',body:'Shopify Says AI Search Boosts Conversions by 80%  PYMNTS.com',src:'https://news.google.com/rss/articles/CBMimwFBVV95cUxONVpGaVBiN3Z3UW1RYXdQRDRjc3lSVDBGRFNxSkdpdzR4Z2htSy15R1ZkdTktbjdoUTROS1VYY29jY0p1d0hXQTB0MU5qWVdGRVdCeXpoZ0JhdGlqZW9nR3dCRTJvbFFkVmpCT1ZIQ1R4SVZEV2VOdHJnUjFhME01M3JlTTJ4b1A5QjhPNTdVYkgyUk84cUlXbnE0UQ?oc=5',via:'PYMNTS'},
{tag:'AMAZON',date:'09/14/2026',title:'Amazon Business Expands Reconciliation Report with Line-Item Detail - Modern Distribution Management',body:'Amazon Business Expands Reconciliation Report with Line-Item Detail  Modern Distribution Management',src:'https://news.google.com/rss/articles/CBMivgFBVV95cUxNaFdEbDlPRjMzQ3ROcXJmZFhoVGI4dHNjeWNRWXJCSUpWLTNVSjBlemdEUkNHOUlLd0RIdFRYQUI3bXVNd1FvS21MYy1ab0RWU0FIUzladTBYOXBTbVU4YUI5R2dCdExFQms0Yjhza2trWmNrOVM4YWRhcDl3WFpTNl9uMTh1N2lCUEVMa3dXRzQyZFYybGwzSS1YMTRscWFoY1E5UEpsdWlLYVlkWVloS3ViYV9CclRxQmVTb3RR?oc=5',via:'Modern Distribution Management'},
{tag:'TIKTOK SHOP',date:'09/14/2026',title:'PrintKK\'s Los Angeles Production Powers TikTok Shop Sellers Through Viral Demand Surges - The Des Moines Register',body:'PrintKK\'s Los Angeles Production Powers TikTok Shop Sellers Through Viral Demand Surges  The Des Moines Register',src:'https://news.google.com/rss/articles/CBMi4gFBVV95cUxORVZkVmxaUURZd3VGWmc1T25GZXRYV2xKUDUzQ0NJeGR3MEgyYmZhSnhIYW05S3R1MEpLankxNW1jRDdya1FpMEN6elliNnBpUU5kaFFnZ0FtSWRpV2JIMUlrY0ZlV19BYWR3T0V4bFRxdzVFelA3dXExdzlzRzNEZ2NEZ1NCaldXZms3UGhEekVYeUxxcHptODY1cFhwTWhvRkxRaElVLXUyOEFMOTZSeVY3ay1VcWh5SnVIRjQxdWkzNUl4TEpzQ3NMMkk1Z2lNMzRRcnRHdGhCeGxLeDRoUFBn?oc=5',via:'The Des Moines Register'},
{tag:'AMAZON',date:'09/14/2026',title:'Amazon gives bundle sellers 4 months to get brand approval or lose listings - PPC Land',body:'Amazon gives bundle sellers 4 months to get brand approval or lose listings  PPC Land',src:'https://news.google.com/rss/articles/CBMimAFBVV95cUxPcGZmX2ktNHR4MXJTUm90dGJOeHdQZlNDSVJTUUZfcG02dFF1SmNLRmRRTnZ2Z2RrOE5XWDYtaC1Cd1Myckt6Tk5HOFYyLVBYVElWd2pkQWZESkpjemluU1JLQnNiMjQ3M05ka0dBU2RSc0JaeHBRX25NbW1kYmZZVkQ2NWRRdmoxZ1FmRmkyREo1VnNGNENnWg?oc=5',via:'PPC Land'},
{tag:'AI',date:'09/14/2026',title:'Agentic commerce is loosening the grocery aisle’s grip on the shopper - The Next Web',body:'Agentic commerce is loosening the grocery aisle’s grip on the shopper  The Next Web',src:'https://news.google.com/rss/articles/CBMibkFVX3lxTFBwbDk5UlNqWnZuSGVObUZCc2x4QmNWQ2dCS2hSTmxDS25iQ29tNDM0N0VRVXFqc3o5RXc2VzMtZC11RkhXcE5XTkhsdGJLNjZlQm9hSjFYaklTN0YxY2hkT1E4TlNnT0d2OFh5bWl3?oc=5',via:'The Next Web'},
{tag:'MARKETPLACE',date:'09/14/2026',title:'US invests in critical minerals but China maintains grip - Reuters',body:'US invests in critical minerals but China maintains grip  Reuters',src:'https://news.google.com/rss/articles/CBMirAFBVV95cUxNMGtsNFhCU1JCWjQ4RGZOTGlxUnBBWGFPM1lRR0l3X3l5QmswT0xzSzdDcXRwS0VtN3JOdjNIUzlUU3Y0T1ViaVdhZ0UyNU1HT1BKbGlQWkJmVUZsc0d0ZGlKeC1LYWI1RXR4UkdmT2RHU25XU3pVamNJMWVOSmtXRUdSeFN4M1BpRHg2eGhGQ1V2THNqa2NkR1I2XzE3Ml9tTldEa1ZDZE1HdEJv?oc=5',via:'Reuters'},
{tag:'SHEIN',date:'09/14/2026',title:'Shein opens automated distribution center in Indiana - Supply Chain Dive',body:'Shein opens automated distribution center in Indiana  Supply Chain Dive',src:'https://news.google.com/rss/articles/CBMingFBVV95cUxNX0FTQ0dHb09XaEVScjJYUXVwU0xWV0Flal83WWpRNG9OYU4tNlIyZnpBcmNMeENNSmFHYmN1YURkNWstczQ3dEhVN1JCR19zYzU5dDlOeEs0emFvdXdhYV9YOHY5cTE5UXVERUxydGRnVndfZ1FTMGNjUVVaSWlKYTk5c0NRTGFna1JIbWw4M0dVNC1RWVhoZ2JiRHFkQQ?oc=5',via:'Supply Chain Dive'},
{tag:'WALMART',date:'09/14/2026',title:'You can soon order Dunkin\' and groceries in one Walmart app trip - finance.yahoo.com',body:'You can soon order Dunkin\' and groceries in one Walmart app trip  finance.yahoo.com',src:'https://news.google.com/rss/articles/CBMisAFBVV95cUxPN0I4SEFzeEcxRXpuUnQ1M3locEtVVXM0aHVucl9vQ2I0RGFMcm96bEdVVkE4cksxLTlHRjlwNkpaX3kxdGI4cE44YlBodFpEWERpUHNUUE9mSVh0UFpWMmo3aE9zM3pWNFE3ZHhRMF9salZVVU50UnlPRWJrZ0h0T0FRSWtxNXEtR1NHRVVJYThSaUNGOWJLS1htQjQ1aXBxNkR4b28yeXhidm9HZ2hGQg?oc=5',via:'Yahoo Finance'},
{tag:'TEMU',date:'09/14/2026',title:'Temu isn’t just for Gen Z: nearly seven out of 10 visitors are Millennials, Gen X, and Boomers - Revista Merca2.0',body:'Temu isn’t just for Gen Z: nearly seven out of 10 visitors are Millennials, Gen X, and Boomers  Revista Merca2.0',src:'https://news.google.com/rss/articles/CBMitgFBVV95cUxQUW02Y3dqekE5X2ZTeEVYOUR4QlVZVkJXcFllZVFmalBKeG43cW4zVENRYkkyTGxmSG5PVWxudnpNOF9BOE9VU0ZPTzctVFBaZURiT2IxVm5WNEFYR2duNHQwZXlRRVRMOFFqVEM2SE9aTzVEQ3MzWTV5dDhsVVQ3VHVTQ1NkTTBfT19nZFhJNWMxWEphUFdldjhLVEhfbXBqdi1zTEd3VWhDQjJVbERsc2xqem9KZw?oc=5',via:'Revista Merca2.0'},
{tag:'SHEIN',date:'09/14/2026',title:'Companies left China to dodge tariffs. Now some are heading back - Reuters',body:'Companies left China to dodge tariffs.',src:'https://news.google.com/rss/articles/CBMivgFBVV95cUxOcXZhYnM4LUVqMVptczRMSnVLLUp2YVVfRm9kNGh2MnZmWVlYUEtERkowb0xsb2drVG12aTd1SVlPNUFiRW9HQjJRNEhVR1hBWjZKem4xTjBaaVZ2anhqdTRscDYwcVZZUmp5V0FncDRPXzhhQ3BZWjc1ZlkyWXFaM0pDTFM0eUU2S0FYaUhvVzFVeUhyREZJZm85V0IzWTBnaGFFM2ZRam4wY1lkTlVTMnBYV2xVclBuTHJTSGZR?oc=5',via:'Reuters'},
{tag:'GOOGLE',date:'09/14/2026',title:'Mastercard’s Sherri Haymond on Letting AI Shop While Consumers Stay in Charge - PYMNTS.com',body:'Mastercard’s Sherri Haymond on Letting AI Shop While Consumers Stay in Charge  PYMNTS.com',src:'https://news.google.com/rss/articles/CBMizwFBVV95cUxNQTY3Y1FlSTFNZVRHTkplZjI3aTlGZ25zMHNmTkdLbGRSNGVYcjB2YWUtY1R6YllSMk1HQWRla2Y3UHlnb2Z4WEQzMlJ1WWpycnhXUVBjLW4tRzhpNVBZRnNuTERHTThmVlpvd1ZrMHZuS1RtMG1uWGg3cktxTnhuOFBpNGY5Zk9ic09STVFETTdNcDc0aWJUamt4VHp3QjZtRGVMZWlzUERIMXFmTnpJUkJMenlTYVdsSGZNUmtvUXlJSmN2YW1vUGZPVU5WSVE?oc=5',via:'PYMNTS'},
{tag:'AMAZON',date:'09/14/2026',title:'Amazon Great Indian Festival 2026 sale dates and deals revealed by Amazon\'s Rufus AI: Here’s what to... - Moneycontrol.com',body:'Amazon Great Indian Festival 2026 sale dates and deals revealed by Amazon\'s Rufus AI: Here’s what to...',src:'https://news.google.com/rss/articles/CBMiggJBVV95cUxNbTFjV3RZUHZNRHVRZS1hd1I3UFJMTmxWNUNoRHppOUNBUllQb1ZKWFRGdWdBdnhyUDlKcjQ5Z2EyX29aLW90ak9IZmJ3YWN3TVBYaTdQTWF3TFZxN1VCbi1RdzZNYk4xZlI1TGVPYVpLQ0hEbFFSRUFONHZlQXpQNlg1YUlZekQtVHBfVXg4T2JPN05uaTJwdU5oZnBuNzlpMlZheXlwNXMxenBxRVg1RXY1UXotWGNwVW4zYWxWUHVRNEhrODc5SDRCWWdJWEVfa2RrNVNveFJjUnRBQV8wSXlaSmkwSHNmWF9QejdxSTgtUWVSMGxqcFpKUmR1bG1hX0HSAYICQVVfeXFMTW0xY1d0WVB2TUR1UWUtYXdSN1BSTE5sVjVDaER6aTlDQVJZUG9WSlhURnVnQXZ4clA5SnI0OWdhMl9vWi1vdGpPSGZid2Fjd01QWGk3UE1hd0xWcTdVQm4tUXc2TWJOMWZSNUxlT2FaS0NIRGxRUkVBTjR2ZUF6UDZYNWFJWXpELVRwX1V4OE9iTzdObmkycHVOaGZwbjc5aTJWYXl5cDVzMXpwcUVYNUV2NVF6LVhjcFVuM2FsVlB1UTRIazg3OUg0QllnSVhFX2tkazVTb3hSY1J0QUFfMEl5WkppMEhzZlhfUHo3cUk4LVFlUjBsanBaSlJkdWxtYV9B?oc=5',via:'Moneycontrol.com'},
{tag:'AMAZON',date:'09/14/2026',title:'Amway Sues Amazon Seller Over Alleged Unauthorised Product Sales - Global Cosmetics News',body:'Amway Sues Amazon Seller Over Alleged Unauthorised Product Sales  Global Cosmetics News',src:'https://news.google.com/rss/articles/CBMiowFBVV95cUxNVHI0T2hVLU5MSGRTSTNid09Eek01cTZQSlBCU1NqOGJxWVdNR3NaeTJ2LWNUSVA1WlpMTGZWVXBvaW9tZFJYckhTb1ZlaTBiRFhEVWhNdjRGbWNKX0dhQmNWZWNQNWI5WXQ1TnNNSTlKWFdvbzZZZ3BfN0VwTVNXVTRKVjlQOXQ4MVBXREpRbTU0Rk5DdzVSaGNDNGlfMzdGdlk0?oc=5',via:'Global Cosmetics News'},
{tag:'EBAY',date:'09/13/2026',title:'Ebay (EBAY) Q1 2026 Earnings Call Transcript - Fortune',body:'Ebay (EBAY) Q1 2026 Earnings Call Transcript  Fortune',src:'https://news.google.com/rss/articles/CBMiX0FVX3lxTE8wZUtyVDZ4YllUbUN6cG04THJ5bWk2ci1LT2VBYTlJZ0dheEtYd01fb1RPUEUtalphWmN1b3hicUxhR21IYVlNU2ZNN0FlSWdYSTU5VllNdXBtLURVYWxF?oc=5',via:'Fortune'},
{tag:'TEMU',date:'09/13/2026',title:'Temu, Shein and AliExpress lose ground in Hungary after new EU customs charge - Daily News Hungary',body:'Temu, Shein and AliExpress lose ground in Hungary after new EU customs charge  Daily News Hungary',src:'https://news.google.com/rss/articles/CBMidkFVX3lxTE44R2RYSUJmdnRkSFJaeEFaX3k2RjBnMU1NTk13VDQ2STJWNEJGbnU2d1V4bThtWi1nYWlXZGRJaHU4WllfZHZlTWlKcVp5TXlEdjBINXFpSnVnNExOR1pNaDlvcTg2UnJVLVJzdXBELTU4WHlQT2c?oc=5',via:'Daily News Hungary'},
{tag:'SCOTUS',date:'09/13/2026',title:'Supreme Court Rules That Trump’s Sweeping Emergency Tariffs Are Illegal - energynow.com',body:'Supreme Court Rules That Trump’s Sweeping Emergency Tariffs Are Illegal  energynow.com',src:'https://news.google.com/rss/articles/CBMiowFBVV95cUxQa09Gd3lobnhkX19sYVlEbE90UTdPTV9SczhXRndqaVU2RWJheXJQWkhIcElyb29fa2hndFFWMy1qbEYzcGtOdUgydXlxbEwzeThmQTVpVmt3S21FZnBkaGh2LU5IX192WnVReUJoZ1pBaWZ6RXBHU09CMzVhMUhHeTZDTmRTc2tnQkVRbGh0UjdZV2lVUkJBV3RKUDJhY2pWMXdB?oc=5',via:'energynow.com'},
{tag:'WALMART',date:'09/13/2026',title:'Does Retail Media Add Value? - Practical Ecommerce',body:'Does Retail Media Add Value?',src:'https://news.google.com/rss/articles/CBMib0FVX3lxTE9tbFJnSk1MSVo2OHhPMlp2N3I2M3U0LTNoRHVFUlU4eURpazAxVGc3Um42cmpxS1l5NU41NGd1Umd3RUw5S0UwZzFkaUZ5ZzRlcFU1MGd1bjlhdlNBcWp1dzNrbTkxYnppXzNsa1Jvaw?oc=5',via:'Practical Ecommerce'},
{tag:'SHEIN / TEMU',date:'09/13/2026',title:'EU to Charge €3 Fee on Shein, Temu Parcels From July 2026 - tovima.com',body:'EU to Charge €3 Fee on Shein, Temu Parcels From July 2026  tovima.com',src:'https://news.google.com/rss/articles/CBMikgFBVV95cUxNWkY5anUyVm5TYUhPS2pLXzhKeTlOTUlMZ0V5RjUzWWJQRmpzWmZNaFhjb2drTGRPcEtPbnZMQ2JMbnpWa0xSOExtTnRnTllFVV9EWV9NMjN0U3o5Zk9yVlVSNDZfM0ZtMVZFWWRqTmQzOHNCek1CX0dPalFESnoxNmJNWlpSUFl1OG5NWk1tYTFsQdIBlwFBVV95cUxPMTZIdzNfRjk4M1hPTXZFcmpxcVVPQXd3aGFhV0ZSVjJrWlBwZW1BNmdMX3RqRDBNMXdERDhYeFVneTJJaEpaWm9LZEZheC1oOUkzcjJUV09QVE0tQlBXaEZLVmwwVEEySkV6LWhCSjJsakhwN1FfbVpxX1lsaE1Ed2txbS1WMjlnY3NxMkJSc3ROTk82Rl84?oc=5',via:'tovima.com'},
{tag:'EBAY',date:'09/13/2026',title:'eBay Inc. $EBAY Shares Acquired by Tidal Investments LLC - MarketBeat',body:'eBay Inc.',src:'https://news.google.com/rss/articles/CBMitgFBVV95cUxOTERLbElVMlB3Z3Z3X0w5M001d3VYam5BY3BGRWZ3ZmFWU3M1dzRBa0VEa2ZFa19MVmE0QlhRWXp0TEhGOUZlRzNhVVM0WUcyc0VPUDU1WmZCbFlvaTM4MUxENlVkRWdBX01MczlERFVBOWtwLTdIbC1BVldyeGRPNFFTRkZnVGlFcWFOMDRocExHb0MydWQ4MFdMc1RnQUlMRmliX3VWSVJRQW80a0tyMnZnNWd0dw?oc=5',via:'MarketBeat'},
{tag:'AI',date:'09/13/2026',title:'Agentic AI will Transform E-Commerce Strategies by 2030 - Technology Magazine',body:'Agentic AI will Transform E-Commerce Strategies by 2030  Technology Magazine',src:'https://news.google.com/rss/articles/CBMilgFBVV95cUxONlltS2szQ1E1YUk1RGIzOHV2SVpsbXZraUF6UEJROFU5Um14Xy16TmhsLXFOODdCRWkzNThZdnAtLWY0VGRlU05zT2FyX0xYYlo3NlZDb3VhRlZ4dWZYbEowUGVVRlByX2tMeG9DWFFXNG5jQ25IazQ4MjVqejE3ZERjbTBFdGJaZWlib29HSmpOSDNBaVE?oc=5',via:'Technology Magazine'},
{tag:'AMAZON',date:'09/13/2026',title:'Amway sues Amazon seller over ‘unlawful sale’ of products - WLNS 6 News',body:'Amway sues Amazon seller over ‘unlawful sale’ of products  WLNS 6 News',src:'https://news.google.com/rss/articles/CBMimwFBVV95cUxOTmRHandoTGdvYTVXYWpjWGFCU3dYSlpNOTVSU3pTVlB3X3RmVkV3T0lFVUw0ekZ1TmJVWXBCOEdET1FpeEl3bU44SWxveDRIWUJZN0x3Z25BV1dUWG9YRDBiQTIwM2N1dk5GN2NHM29VVTNSdlBDSHRUZVY0Yl8tTDF5eGh3bUYtZlJZNVZPcndIM0k1R1VOdVk3MNIBmwFBVV95cUxOTmRHandoTGdvYTVXYWpjWGFCU3dYSlpNOTVSU3pTVlB3X3RmVkV3T0lFVUw0ekZ1TmJVWXBCOEdET1FpeEl3bU44SWxveDRIWUJZN0x3Z25BV1dUWG9YRDBiQTIwM2N1dk5GN2NHM29VVTNSdlBDSHRUZVY0Yl8tTDF5eGh3bUYtZlJZNVZPcndIM0k1R1VOdVk3MA?oc=5',via:'WLNS 6 News'},
{tag:'AMAZON',date:'09/13/2026',title:'Amazon blocks the failing FBM offer, not the account, from August 31 - PPC Land',body:'Amazon blocks the failing FBM offer, not the account, from August 31  PPC Land',src:'https://news.google.com/rss/articles/CBMijAFBVV95cUxOODk5YXhvemp3Nkw4dG0xRHRIMFozT2pFUTVUUkJySThyTUh2N1plalZ6T0ZxWTVUNThmTC1OMWNsZ1pOZjhxUVNrcUNBcHRzdU14QTl1amJJZTc3TVZXcl9IX09CV2wxRlVoN01BX2hwNHFvVWhSZTMzRlBYU2FaMUpGOWF3NkdiN0hIZA?oc=5',via:'PPC Land'},
{tag:'JD.COM',date:'09/12/2026',title:'JD.com (JD) Looks Fully Valued As Joybuy Deal Puts Fresh Focus On Valuation - simplywall.st',body:'JD.com (JD) Looks Fully Valued As Joybuy Deal Puts Fresh Focus On Valuation  simplywall.st',src:'https://news.google.com/rss/articles/CBMiuwFBVV95cUxONGxGcTMxREZNVGV2VEJxXzRheTFZY1hjYzBTMzlGSHItU05zU1J2b1JXUlJ1eTE2dVJYZnI1b3d4VmVvN2V0S0JSbk9xVE9OemdBaGZ6QmZmT19RY1VxQTd3aG5VUHBhM2ZUUzRtR1VfUU14Q0dTUHJwdXlfUTRlWGV1Ung1OWxBLUk4NnJ1X0lpbklOd0RfenZxMGluRVR2TV9UYnJNODdzSzV2ZEktVG5SekY2cWFQOXBn0gHAAUFVX3lxTFBJdXdRMDdNb2Y4dWF0S0lWampaXzMzeXRpbmtkNnI4RmZYWUV5TTJNU3c1aEVfUEczcDIxeWY3V25SbnJxTVdqeGFXTDlWUklMVXZJb2RyWkJ5elY2aExhMjVxU3RLczNaaXRWUGtTZ0k3czZTTXllOVdmU2RfZjA4XzVfLXB2a0N3dGMxZ2VGRVpPMlFyYzJTS2k1a21RNlBCOEZrMUpHcXFyYXpWTmUwMGs3alRCMVhva1ZXd1F0Zg?oc=5',via:'simplywall.st'}
];
const DAILY_SUMMARY={
  date:'2026/09/15',
  points:[
  ]
};
